export interface NpaInfo {
  country: "US" | "CA" | "NANP";
  state: string;
  stateAbbr: string;
  region: string;
  timezone: string;
}

const NPA_DATABASE: Record<string, NpaInfo> = {
  // ── Alabama ──────────────────────────────────────────────────────────────────
  "205": { country:"US", state:"Alabama", stateAbbr:"AL", region:"Birmingham metro", timezone:"America/Chicago" },
  "251": { country:"US", state:"Alabama", stateAbbr:"AL", region:"Mobile / SW Alabama", timezone:"America/Chicago" },
  "256": { country:"US", state:"Alabama", stateAbbr:"AL", region:"Huntsville / N Alabama", timezone:"America/Chicago" },
  "334": { country:"US", state:"Alabama", stateAbbr:"AL", region:"Montgomery / Central-South Alabama", timezone:"America/Chicago" },
  "938": { country:"US", state:"Alabama", stateAbbr:"AL", region:"N Alabama (overlay)", timezone:"America/Chicago" },
  // ── Alaska ───────────────────────────────────────────────────────────────────
  "907": { country:"US", state:"Alaska", stateAbbr:"AK", region:"Statewide", timezone:"America/Anchorage" },
  // ── Arizona ──────────────────────────────────────────────────────────────────
  "480": { country:"US", state:"Arizona", stateAbbr:"AZ", region:"E Phoenix metro (Scottsdale, Mesa, Tempe)", timezone:"America/Phoenix" },
  "520": { country:"US", state:"Arizona", stateAbbr:"AZ", region:"S Arizona (Tucson, Sierra Vista)", timezone:"America/Phoenix" },
  "602": { country:"US", state:"Arizona", stateAbbr:"AZ", region:"Phoenix core", timezone:"America/Phoenix" },
  "623": { country:"US", state:"Arizona", stateAbbr:"AZ", region:"W Phoenix metro (Glendale, Peoria)", timezone:"America/Phoenix" },
  "928": { country:"US", state:"Arizona", stateAbbr:"AZ", region:"N/Rural Arizona (Flagstaff, Yuma, Prescott)", timezone:"America/Phoenix" },
  // ── Arkansas ─────────────────────────────────────────────────────────────────
  "479": { country:"US", state:"Arkansas", stateAbbr:"AR", region:"NW Arkansas (Fayetteville, Fort Smith)", timezone:"America/Chicago" },
  "501": { country:"US", state:"Arkansas", stateAbbr:"AR", region:"Central Arkansas (Little Rock)", timezone:"America/Chicago" },
  "870": { country:"US", state:"Arkansas", stateAbbr:"AR", region:"E/S Arkansas", timezone:"America/Chicago" },
  // ── California ───────────────────────────────────────────────────────────────
  "209": { country:"US", state:"California", stateAbbr:"CA", region:"Central Valley (Stockton, Modesto)", timezone:"America/Los_Angeles" },
  "213": { country:"US", state:"California", stateAbbr:"CA", region:"Los Angeles (central)", timezone:"America/Los_Angeles" },
  "279": { country:"US", state:"California", stateAbbr:"CA", region:"Sacramento (overlay)", timezone:"America/Los_Angeles" },
  "310": { country:"US", state:"California", stateAbbr:"CA", region:"W Los Angeles (Beverly Hills, Santa Monica)", timezone:"America/Los_Angeles" },
  "323": { country:"US", state:"California", stateAbbr:"CA", region:"E/S Los Angeles (Hollywood, Compton)", timezone:"America/Los_Angeles" },
  "341": { country:"US", state:"California", stateAbbr:"CA", region:"East Bay (overlay)", timezone:"America/Los_Angeles" },
  "408": { country:"US", state:"California", stateAbbr:"CA", region:"Silicon Valley (San Jose, Santa Clara)", timezone:"America/Los_Angeles" },
  "415": { country:"US", state:"California", stateAbbr:"CA", region:"San Francisco", timezone:"America/Los_Angeles" },
  "424": { country:"US", state:"California", stateAbbr:"CA", region:"W Los Angeles (overlay)", timezone:"America/Los_Angeles" },
  "442": { country:"US", state:"California", stateAbbr:"CA", region:"San Diego north / Palm Desert (overlay)", timezone:"America/Los_Angeles" },
  "510": { country:"US", state:"California", stateAbbr:"CA", region:"East Bay (Oakland, Berkeley, Fremont)", timezone:"America/Los_Angeles" },
  "530": { country:"US", state:"California", stateAbbr:"CA", region:"N California (Redding, Chico, Sacramento rural)", timezone:"America/Los_Angeles" },
  "559": { country:"US", state:"California", stateAbbr:"CA", region:"Central Valley (Fresno, Visalia)", timezone:"America/Los_Angeles" },
  "562": { country:"US", state:"California", stateAbbr:"CA", region:"SE Los Angeles (Long Beach, Whittier)", timezone:"America/Los_Angeles" },
  "619": { country:"US", state:"California", stateAbbr:"CA", region:"San Diego", timezone:"America/Los_Angeles" },
  "626": { country:"US", state:"California", stateAbbr:"CA", region:"San Gabriel Valley (Pasadena, Glendale)", timezone:"America/Los_Angeles" },
  "628": { country:"US", state:"California", stateAbbr:"CA", region:"San Francisco (overlay)", timezone:"America/Los_Angeles" },
  "650": { country:"US", state:"California", stateAbbr:"CA", region:"Peninsula (Palo Alto, San Mateo)", timezone:"America/Los_Angeles" },
  "657": { country:"US", state:"California", stateAbbr:"CA", region:"Orange County (overlay)", timezone:"America/Los_Angeles" },
  "661": { country:"US", state:"California", stateAbbr:"CA", region:"Bakersfield / Antelope Valley", timezone:"America/Los_Angeles" },
  "669": { country:"US", state:"California", stateAbbr:"CA", region:"Silicon Valley (overlay)", timezone:"America/Los_Angeles" },
  "707": { country:"US", state:"California", stateAbbr:"CA", region:"North Bay (Santa Rosa, Napa, Vallejo)", timezone:"America/Los_Angeles" },
  "714": { country:"US", state:"California", stateAbbr:"CA", region:"Orange County (Anaheim, Santa Ana)", timezone:"America/Los_Angeles" },
  "747": { country:"US", state:"California", stateAbbr:"CA", region:"San Fernando Valley (overlay)", timezone:"America/Los_Angeles" },
  "760": { country:"US", state:"California", stateAbbr:"CA", region:"Desert / San Diego north inland (Palm Springs)", timezone:"America/Los_Angeles" },
  "764": { country:"US", state:"California", stateAbbr:"CA", region:"East Bay (overlay)", timezone:"America/Los_Angeles" },
  "805": { country:"US", state:"California", stateAbbr:"CA", region:"Central Coast (Santa Barbara, Ventura)", timezone:"America/Los_Angeles" },
  "818": { country:"US", state:"California", stateAbbr:"CA", region:"San Fernando Valley (Burbank, Van Nuys)", timezone:"America/Los_Angeles" },
  "820": { country:"US", state:"California", stateAbbr:"CA", region:"Central Coast (overlay)", timezone:"America/Los_Angeles" },
  "831": { country:"US", state:"California", stateAbbr:"CA", region:"Monterey Bay (Monterey, Santa Cruz)", timezone:"America/Los_Angeles" },
  "858": { country:"US", state:"California", stateAbbr:"CA", region:"San Diego north (Miramar, Sorrento Valley)", timezone:"America/Los_Angeles" },
  "909": { country:"US", state:"California", stateAbbr:"CA", region:"Inland Empire (San Bernardino, Ontario)", timezone:"America/Los_Angeles" },
  "916": { country:"US", state:"California", stateAbbr:"CA", region:"Sacramento metro", timezone:"America/Los_Angeles" },
  "925": { country:"US", state:"California", stateAbbr:"CA", region:"E Bay suburbs (Walnut Creek, Concord)", timezone:"America/Los_Angeles" },
  "949": { country:"US", state:"California", stateAbbr:"CA", region:"S Orange County (Irvine, Newport Beach)", timezone:"America/Los_Angeles" },
  "951": { country:"US", state:"California", stateAbbr:"CA", region:"Riverside / Inland Empire south", timezone:"America/Los_Angeles" },
  // ── Colorado ─────────────────────────────────────────────────────────────────
  "303": { country:"US", state:"Colorado", stateAbbr:"CO", region:"Denver metro", timezone:"America/Denver" },
  "719": { country:"US", state:"Colorado", stateAbbr:"CO", region:"S Colorado (Colorado Springs, Pueblo)", timezone:"America/Denver" },
  "720": { country:"US", state:"Colorado", stateAbbr:"CO", region:"Denver metro (overlay)", timezone:"America/Denver" },
  "970": { country:"US", state:"Colorado", stateAbbr:"CO", region:"W/N Colorado (Fort Collins, Grand Junction)", timezone:"America/Denver" },
  // ── Connecticut ──────────────────────────────────────────────────────────────
  "203": { country:"US", state:"Connecticut", stateAbbr:"CT", region:"SW Connecticut (Bridgeport, New Haven)", timezone:"America/New_York" },
  "475": { country:"US", state:"Connecticut", stateAbbr:"CT", region:"SW Connecticut (overlay)", timezone:"America/New_York" },
  "860": { country:"US", state:"Connecticut", stateAbbr:"CT", region:"N/E Connecticut (Hartford, New London)", timezone:"America/New_York" },
  "959": { country:"US", state:"Connecticut", stateAbbr:"CT", region:"N/E Connecticut (overlay)", timezone:"America/New_York" },
  // ── Delaware ─────────────────────────────────────────────────────────────────
  "302": { country:"US", state:"Delaware", stateAbbr:"DE", region:"Statewide", timezone:"America/New_York" },
  // ── D.C. ─────────────────────────────────────────────────────────────────────
  "202": { country:"US", state:"District of Columbia", stateAbbr:"DC", region:"Washington D.C.", timezone:"America/New_York" },
  // ── Florida ──────────────────────────────────────────────────────────────────
  "239": { country:"US", state:"Florida", stateAbbr:"FL", region:"SW Florida (Naples, Fort Myers)", timezone:"America/New_York" },
  "305": { country:"US", state:"Florida", stateAbbr:"FL", region:"Miami / South Florida", timezone:"America/New_York" },
  "321": { country:"US", state:"Florida", stateAbbr:"FL", region:"Space Coast (Brevard County, Orlando area)", timezone:"America/New_York" },
  "352": { country:"US", state:"Florida", stateAbbr:"FL", region:"N-Central Florida (Gainesville, Ocala)", timezone:"America/New_York" },
  "386": { country:"US", state:"Florida", stateAbbr:"FL", region:"NE Florida (Daytona Beach, Flagler)", timezone:"America/New_York" },
  "407": { country:"US", state:"Florida", stateAbbr:"FL", region:"Orlando metro", timezone:"America/New_York" },
  "448": { country:"US", state:"Florida", stateAbbr:"FL", region:"Orlando (overlay)", timezone:"America/New_York" },
  "561": { country:"US", state:"Florida", stateAbbr:"FL", region:"Palm Beach area", timezone:"America/New_York" },
  "689": { country:"US", state:"Florida", stateAbbr:"FL", region:"Orlando (overlay)", timezone:"America/New_York" },
  "727": { country:"US", state:"Florida", stateAbbr:"FL", region:"St. Petersburg / Pinellas County", timezone:"America/New_York" },
  "754": { country:"US", state:"Florida", stateAbbr:"FL", region:"Broward County (overlay)", timezone:"America/New_York" },
  "772": { country:"US", state:"Florida", stateAbbr:"FL", region:"Treasure Coast (Stuart, Fort Pierce)", timezone:"America/New_York" },
  "786": { country:"US", state:"Florida", stateAbbr:"FL", region:"Miami (overlay)", timezone:"America/New_York" },
  "813": { country:"US", state:"Florida", stateAbbr:"FL", region:"Tampa metro", timezone:"America/New_York" },
  "850": { country:"US", state:"Florida", stateAbbr:"FL", region:"Florida Panhandle (Tallahassee, Pensacola)", timezone:"America/Chicago" },
  "863": { country:"US", state:"Florida", stateAbbr:"FL", region:"Central Florida (Lakeland, Polk County)", timezone:"America/New_York" },
  "904": { country:"US", state:"Florida", stateAbbr:"FL", region:"Jacksonville / NE Florida", timezone:"America/New_York" },
  "941": { country:"US", state:"Florida", stateAbbr:"FL", region:"SW Florida (Sarasota, Bradenton)", timezone:"America/New_York" },
  "954": { country:"US", state:"Florida", stateAbbr:"FL", region:"Broward County (Fort Lauderdale)", timezone:"America/New_York" },
  // ── Georgia ──────────────────────────────────────────────────────────────────
  "229": { country:"US", state:"Georgia", stateAbbr:"GA", region:"SW Georgia (Albany, Valdosta)", timezone:"America/New_York" },
  "404": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Atlanta core", timezone:"America/New_York" },
  "470": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Atlanta (overlay)", timezone:"America/New_York" },
  "478": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Central Georgia (Macon, Warner Robins)", timezone:"America/New_York" },
  "678": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Atlanta suburbs (overlay)", timezone:"America/New_York" },
  "706": { country:"US", state:"Georgia", stateAbbr:"GA", region:"N/W Georgia (Augusta, Columbus)", timezone:"America/New_York" },
  "762": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Augusta area (overlay)", timezone:"America/New_York" },
  "770": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Atlanta suburbs", timezone:"America/New_York" },
  "912": { country:"US", state:"Georgia", stateAbbr:"GA", region:"Savannah / SE Georgia", timezone:"America/New_York" },
  // ── Hawaii ───────────────────────────────────────────────────────────────────
  "808": { country:"US", state:"Hawaii", stateAbbr:"HI", region:"Statewide", timezone:"Pacific/Honolulu" },
  // ── Idaho ────────────────────────────────────────────────────────────────────
  "208": { country:"US", state:"Idaho", stateAbbr:"ID", region:"Statewide", timezone:"America/Denver" },
  "986": { country:"US", state:"Idaho", stateAbbr:"ID", region:"Statewide (overlay)", timezone:"America/Denver" },
  // ── Illinois ─────────────────────────────────────────────────────────────────
  "217": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Central Illinois (Springfield, Champaign)", timezone:"America/Chicago" },
  "224": { country:"US", state:"Illinois", stateAbbr:"IL", region:"N Chicago suburbs (overlay)", timezone:"America/Chicago" },
  "309": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Central-W Illinois (Peoria, Bloomington)", timezone:"America/Chicago" },
  "312": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Chicago core (Loop, downtown)", timezone:"America/Chicago" },
  "331": { country:"US", state:"Illinois", stateAbbr:"IL", region:"W Chicago suburbs (overlay)", timezone:"America/Chicago" },
  "447": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Central Illinois (overlay)", timezone:"America/Chicago" },
  "618": { country:"US", state:"Illinois", stateAbbr:"IL", region:"S Illinois (East St. Louis, Carbondale)", timezone:"America/Chicago" },
  "630": { country:"US", state:"Illinois", stateAbbr:"IL", region:"W Chicago suburbs (Naperville, Wheaton)", timezone:"America/Chicago" },
  "708": { country:"US", state:"Illinois", stateAbbr:"IL", region:"S/W Chicago suburbs", timezone:"America/Chicago" },
  "773": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Chicago (non-core neighborhoods)", timezone:"America/Chicago" },
  "779": { country:"US", state:"Illinois", stateAbbr:"IL", region:"N Illinois (Rockford, overlay)", timezone:"America/Chicago" },
  "815": { country:"US", state:"Illinois", stateAbbr:"IL", region:"N/Central Illinois (Joliet, Rockford)", timezone:"America/Chicago" },
  "847": { country:"US", state:"Illinois", stateAbbr:"IL", region:"N Chicago suburbs (Evanston, Waukegan)", timezone:"America/Chicago" },
  "872": { country:"US", state:"Illinois", stateAbbr:"IL", region:"Chicago (overlay)", timezone:"America/Chicago" },
  // ── Indiana ──────────────────────────────────────────────────────────────────
  "219": { country:"US", state:"Indiana", stateAbbr:"IN", region:"NW Indiana / Chicago suburbs (Gary, Hammond)", timezone:"America/Chicago" },
  "260": { country:"US", state:"Indiana", stateAbbr:"IN", region:"NE Indiana (Fort Wayne)", timezone:"America/Indiana/Indianapolis" },
  "317": { country:"US", state:"Indiana", stateAbbr:"IN", region:"Indianapolis metro", timezone:"America/Indiana/Indianapolis" },
  "463": { country:"US", state:"Indiana", stateAbbr:"IN", region:"Indianapolis (overlay)", timezone:"America/Indiana/Indianapolis" },
  "574": { country:"US", state:"Indiana", stateAbbr:"IN", region:"N-Central Indiana (South Bend, Elkhart)", timezone:"America/Indiana/Indianapolis" },
  "765": { country:"US", state:"Indiana", stateAbbr:"IN", region:"Central Indiana (Muncie, Lafayette)", timezone:"America/Indiana/Indianapolis" },
  "812": { country:"US", state:"Indiana", stateAbbr:"IN", region:"S Indiana (Evansville, Bloomington)", timezone:"America/Indiana/Indianapolis" },
  "930": { country:"US", state:"Indiana", stateAbbr:"IN", region:"S Indiana (overlay)", timezone:"America/Indiana/Indianapolis" },
  // ── Iowa ─────────────────────────────────────────────────────────────────────
  "319": { country:"US", state:"Iowa", stateAbbr:"IA", region:"E Iowa (Cedar Rapids, Iowa City)", timezone:"America/Chicago" },
  "515": { country:"US", state:"Iowa", stateAbbr:"IA", region:"Central Iowa (Des Moines)", timezone:"America/Chicago" },
  "563": { country:"US", state:"Iowa", stateAbbr:"IA", region:"NE Iowa (Dubuque, Davenport)", timezone:"America/Chicago" },
  "641": { country:"US", state:"Iowa", stateAbbr:"IA", region:"Central Iowa (rural)", timezone:"America/Chicago" },
  "712": { country:"US", state:"Iowa", stateAbbr:"IA", region:"W Iowa (Council Bluffs, Sioux City)", timezone:"America/Chicago" },
  // ── Kansas ───────────────────────────────────────────────────────────────────
  "316": { country:"US", state:"Kansas", stateAbbr:"KS", region:"S-Central Kansas (Wichita)", timezone:"America/Chicago" },
  "620": { country:"US", state:"Kansas", stateAbbr:"KS", region:"S Kansas (Dodge City, Garden City)", timezone:"America/Chicago" },
  "785": { country:"US", state:"Kansas", stateAbbr:"KS", region:"N/W Kansas (Topeka, Lawrence, Manhattan)", timezone:"America/Chicago" },
  "913": { country:"US", state:"Kansas", stateAbbr:"KS", region:"NE Kansas / KC suburb (Overland Park)", timezone:"America/Chicago" },
  // ── Kentucky ─────────────────────────────────────────────────────────────────
  "270": { country:"US", state:"Kentucky", stateAbbr:"KY", region:"W Kentucky (Bowling Green, Paducah)", timezone:"America/Chicago" },
  "364": { country:"US", state:"Kentucky", stateAbbr:"KY", region:"W Kentucky (overlay)", timezone:"America/Chicago" },
  "502": { country:"US", state:"Kentucky", stateAbbr:"KY", region:"N-Central Kentucky (Louisville, Frankfort)", timezone:"America/New_York" },
  "606": { country:"US", state:"Kentucky", stateAbbr:"KY", region:"E Kentucky (Ashland, Pikeville)", timezone:"America/New_York" },
  "859": { country:"US", state:"Kentucky", stateAbbr:"KY", region:"Central Kentucky (Lexington, Covington)", timezone:"America/New_York" },
  // ── Louisiana ────────────────────────────────────────────────────────────────
  "225": { country:"US", state:"Louisiana", stateAbbr:"LA", region:"Baton Rouge metro", timezone:"America/Chicago" },
  "318": { country:"US", state:"Louisiana", stateAbbr:"LA", region:"N Louisiana (Shreveport, Monroe)", timezone:"America/Chicago" },
  "337": { country:"US", state:"Louisiana", stateAbbr:"LA", region:"SW Louisiana (Lafayette, Lake Charles)", timezone:"America/Chicago" },
  "504": { country:"US", state:"Louisiana", stateAbbr:"LA", region:"New Orleans metro", timezone:"America/Chicago" },
  "985": { country:"US", state:"Louisiana", stateAbbr:"LA", region:"SE Louisiana (Slidell, Houma)", timezone:"America/Chicago" },
  // ── Maine ────────────────────────────────────────────────────────────────────
  "207": { country:"US", state:"Maine", stateAbbr:"ME", region:"Statewide (Portland, Bangor, Augusta)", timezone:"America/New_York" },
  // ── Maryland ─────────────────────────────────────────────────────────────────
  "240": { country:"US", state:"Maryland", stateAbbr:"MD", region:"W/Central Maryland (Rockville, Frederick)", timezone:"America/New_York" },
  "301": { country:"US", state:"Maryland", stateAbbr:"MD", region:"W/Central Maryland", timezone:"America/New_York" },
  "410": { country:"US", state:"Maryland", stateAbbr:"MD", region:"Baltimore metro", timezone:"America/New_York" },
  "443": { country:"US", state:"Maryland", stateAbbr:"MD", region:"Baltimore / Maryland (overlay)", timezone:"America/New_York" },
  "667": { country:"US", state:"Maryland", stateAbbr:"MD", region:"Baltimore / Maryland (overlay)", timezone:"America/New_York" },
  // ── Massachusetts ────────────────────────────────────────────────────────────
  "339": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"E Massachusetts (overlay)", timezone:"America/New_York" },
  "351": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"NE Massachusetts (overlay)", timezone:"America/New_York" },
  "413": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"W Massachusetts (Springfield, Northampton)", timezone:"America/New_York" },
  "508": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"Central/SE Massachusetts (Worcester, Cape Cod)", timezone:"America/New_York" },
  "617": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"Boston metro core", timezone:"America/New_York" },
  "774": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"Central/SE Massachusetts (overlay)", timezone:"America/New_York" },
  "781": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"N/S Shore Boston suburbs", timezone:"America/New_York" },
  "857": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"Boston (overlay)", timezone:"America/New_York" },
  "978": { country:"US", state:"Massachusetts", stateAbbr:"MA", region:"NE Massachusetts (Lowell, Lawrence)", timezone:"America/New_York" },
  // ── Michigan ─────────────────────────────────────────────────────────────────
  "231": { country:"US", state:"Michigan", stateAbbr:"MI", region:"NW Michigan (Traverse City, Muskegon)", timezone:"America/Detroit" },
  "248": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Oakland County (N Detroit suburbs)", timezone:"America/Detroit" },
  "269": { country:"US", state:"Michigan", stateAbbr:"MI", region:"SW Michigan (Kalamazoo, Battle Creek)", timezone:"America/Detroit" },
  "313": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Detroit / Wayne County", timezone:"America/Detroit" },
  "517": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Central Michigan (Lansing, Jackson)", timezone:"America/Detroit" },
  "586": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Macomb County (NE Detroit suburbs)", timezone:"America/Detroit" },
  "616": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Grand Rapids area", timezone:"America/Detroit" },
  "734": { country:"US", state:"Michigan", stateAbbr:"MI", region:"SE Michigan (Ann Arbor, Monroe)", timezone:"America/Detroit" },
  "810": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Flint area / SE Michigan", timezone:"America/Detroit" },
  "906": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Upper Peninsula", timezone:"America/Chicago" },
  "947": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Oakland County (overlay)", timezone:"America/Detroit" },
  "989": { country:"US", state:"Michigan", stateAbbr:"MI", region:"Central/NE Michigan (Saginaw, Bay City)", timezone:"America/Detroit" },
  // ── Minnesota ────────────────────────────────────────────────────────────────
  "218": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"N Minnesota (Duluth, Bemidji)", timezone:"America/Chicago" },
  "320": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"Central Minnesota (St. Cloud)", timezone:"America/Chicago" },
  "507": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"S Minnesota (Rochester, Mankato)", timezone:"America/Chicago" },
  "612": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"Minneapolis metro core", timezone:"America/Chicago" },
  "651": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"St. Paul / E Twin Cities", timezone:"America/Chicago" },
  "763": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"NW Twin Cities suburbs", timezone:"America/Chicago" },
  "952": { country:"US", state:"Minnesota", stateAbbr:"MN", region:"SW Twin Cities suburbs", timezone:"America/Chicago" },
  // ── Mississippi ──────────────────────────────────────────────────────────────
  "228": { country:"US", state:"Mississippi", stateAbbr:"MS", region:"S Mississippi (Gulfport, Biloxi)", timezone:"America/Chicago" },
  "601": { country:"US", state:"Mississippi", stateAbbr:"MS", region:"Central/S Mississippi (Jackson)", timezone:"America/Chicago" },
  "662": { country:"US", state:"Mississippi", stateAbbr:"MS", region:"N Mississippi (Tupelo, Oxford, Greenville)", timezone:"America/Chicago" },
  "769": { country:"US", state:"Mississippi", stateAbbr:"MS", region:"Mississippi (overlay)", timezone:"America/Chicago" },
  // ── Missouri ─────────────────────────────────────────────────────────────────
  "314": { country:"US", state:"Missouri", stateAbbr:"MO", region:"St. Louis metro core", timezone:"America/Chicago" },
  "417": { country:"US", state:"Missouri", stateAbbr:"MO", region:"SW Missouri (Springfield, Joplin)", timezone:"America/Chicago" },
  "557": { country:"US", state:"Missouri", stateAbbr:"MO", region:"St. Louis (overlay)", timezone:"America/Chicago" },
  "573": { country:"US", state:"Missouri", stateAbbr:"MO", region:"Central/SE Missouri (Columbia, Cape Girardeau)", timezone:"America/Chicago" },
  "636": { country:"US", state:"Missouri", stateAbbr:"MO", region:"St. Louis W suburbs (St. Charles)", timezone:"America/Chicago" },
  "660": { country:"US", state:"Missouri", stateAbbr:"MO", region:"N Missouri (Sedalia, Kirksville)", timezone:"America/Chicago" },
  "816": { country:"US", state:"Missouri", stateAbbr:"MO", region:"Kansas City metro", timezone:"America/Chicago" },
  // ── Montana ──────────────────────────────────────────────────────────────────
  "406": { country:"US", state:"Montana", stateAbbr:"MT", region:"Statewide (Billings, Missoula, Great Falls)", timezone:"America/Denver" },
  // ── Nebraska ─────────────────────────────────────────────────────────────────
  "308": { country:"US", state:"Nebraska", stateAbbr:"NE", region:"W/Central Nebraska (Grand Island, North Platte)", timezone:"America/Chicago" },
  "402": { country:"US", state:"Nebraska", stateAbbr:"NE", region:"E Nebraska (Omaha, Lincoln)", timezone:"America/Chicago" },
  "531": { country:"US", state:"Nebraska", stateAbbr:"NE", region:"E Nebraska (overlay)", timezone:"America/Chicago" },
  // ── Nevada ───────────────────────────────────────────────────────────────────
  "702": { country:"US", state:"Nevada", stateAbbr:"NV", region:"Las Vegas metro", timezone:"America/Los_Angeles" },
  "725": { country:"US", state:"Nevada", stateAbbr:"NV", region:"Las Vegas (overlay)", timezone:"America/Los_Angeles" },
  "775": { country:"US", state:"Nevada", stateAbbr:"NV", region:"N/Rural Nevada (Reno, Carson City)", timezone:"America/Los_Angeles" },
  // ── New Hampshire ────────────────────────────────────────────────────────────
  "603": { country:"US", state:"New Hampshire", stateAbbr:"NH", region:"Statewide (Manchester, Nashua, Concord)", timezone:"America/New_York" },
  // ── New Jersey ───────────────────────────────────────────────────────────────
  "201": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"NE NJ (Jersey City, Hackensack)", timezone:"America/New_York" },
  "551": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"NE NJ (overlay)", timezone:"America/New_York" },
  "609": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"S NJ (Trenton, Atlantic City)", timezone:"America/New_York" },
  "640": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"S NJ (overlay)", timezone:"America/New_York" },
  "732": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"Central NJ (New Brunswick, Asbury Park)", timezone:"America/New_York" },
  "848": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"Central NJ (overlay)", timezone:"America/New_York" },
  "856": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"SW NJ (Cherry Hill, Camden)", timezone:"America/New_York" },
  "862": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"N NJ (Newark, Paterson, overlay)", timezone:"America/New_York" },
  "908": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"Central NJ (Elizabeth, Somerville)", timezone:"America/New_York" },
  "973": { country:"US", state:"New Jersey", stateAbbr:"NJ", region:"N NJ (Newark, Morristown, Passaic)", timezone:"America/New_York" },
  // ── New Mexico ───────────────────────────────────────────────────────────────
  "505": { country:"US", state:"New Mexico", stateAbbr:"NM", region:"N/Central NM (Albuquerque, Santa Fe)", timezone:"America/Denver" },
  "575": { country:"US", state:"New Mexico", stateAbbr:"NM", region:"S/Rural NM (Las Cruces, Roswell)", timezone:"America/Denver" },
  // ── New York ─────────────────────────────────────────────────────────────────
  "212": { country:"US", state:"New York", stateAbbr:"NY", region:"Manhattan core", timezone:"America/New_York" },
  "315": { country:"US", state:"New York", stateAbbr:"NY", region:"Central/N NY (Syracuse, Utica, Watertown)", timezone:"America/New_York" },
  "332": { country:"US", state:"New York", stateAbbr:"NY", region:"Manhattan (overlay)", timezone:"America/New_York" },
  "347": { country:"US", state:"New York", stateAbbr:"NY", region:"NYC outer boroughs (overlay)", timezone:"America/New_York" },
  "516": { country:"US", state:"New York", stateAbbr:"NY", region:"Nassau County (Long Island)", timezone:"America/New_York" },
  "518": { country:"US", state:"New York", stateAbbr:"NY", region:"Capital District (Albany, Schenectady, Saratoga)", timezone:"America/New_York" },
  "585": { country:"US", state:"New York", stateAbbr:"NY", region:"W NY (Rochester)", timezone:"America/New_York" },
  "607": { country:"US", state:"New York", stateAbbr:"NY", region:"Southern Tier (Binghamton, Ithaca, Elmira)", timezone:"America/New_York" },
  "631": { country:"US", state:"New York", stateAbbr:"NY", region:"Suffolk County (Long Island)", timezone:"America/New_York" },
  "646": { country:"US", state:"New York", stateAbbr:"NY", region:"Manhattan (overlay)", timezone:"America/New_York" },
  "680": { country:"US", state:"New York", stateAbbr:"NY", region:"Central/N NY (overlay)", timezone:"America/New_York" },
  "716": { country:"US", state:"New York", stateAbbr:"NY", region:"W NY (Buffalo, Niagara Falls)", timezone:"America/New_York" },
  "718": { country:"US", state:"New York", stateAbbr:"NY", region:"NYC outer boroughs (Brooklyn, Queens, Bronx)", timezone:"America/New_York" },
  "838": { country:"US", state:"New York", stateAbbr:"NY", region:"Capital District (overlay)", timezone:"America/New_York" },
  "845": { country:"US", state:"New York", stateAbbr:"NY", region:"Hudson Valley (Poughkeepsie, Newburgh)", timezone:"America/New_York" },
  "914": { country:"US", state:"New York", stateAbbr:"NY", region:"Westchester County (White Plains, Yonkers)", timezone:"America/New_York" },
  "917": { country:"US", state:"New York", stateAbbr:"NY", region:"NYC (mobile/overlay)", timezone:"America/New_York" },
  "929": { country:"US", state:"New York", stateAbbr:"NY", region:"NYC (overlay)", timezone:"America/New_York" },
  "934": { country:"US", state:"New York", stateAbbr:"NY", region:"Suffolk County (overlay)", timezone:"America/New_York" },
  // ── North Carolina ───────────────────────────────────────────────────────────
  "252": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"E NC (Rocky Mount, Greenville)", timezone:"America/New_York" },
  "336": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Piedmont Triad (Greensboro, Winston-Salem)", timezone:"America/New_York" },
  "704": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Charlotte metro", timezone:"America/New_York" },
  "743": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Greensboro / Triad (overlay)", timezone:"America/New_York" },
  "828": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"W NC (Asheville, Boone)", timezone:"America/New_York" },
  "910": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Cape Fear / SE NC (Wilmington, Fayetteville)", timezone:"America/New_York" },
  "919": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Research Triangle (Raleigh, Durham, Chapel Hill)", timezone:"America/New_York" },
  "980": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Charlotte (overlay)", timezone:"America/New_York" },
  "984": { country:"US", state:"North Carolina", stateAbbr:"NC", region:"Research Triangle (overlay)", timezone:"America/New_York" },
  // ── North Dakota ─────────────────────────────────────────────────────────────
  "701": { country:"US", state:"North Dakota", stateAbbr:"ND", region:"Statewide (Fargo, Bismarck, Grand Forks)", timezone:"America/Chicago" },
  // ── Ohio ─────────────────────────────────────────────────────────────────────
  "216": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Cleveland metro core", timezone:"America/New_York" },
  "220": { country:"US", state:"Ohio", stateAbbr:"OH", region:"SE/Central Ohio (overlay)", timezone:"America/New_York" },
  "234": { country:"US", state:"Ohio", stateAbbr:"OH", region:"NE Ohio (Akron, Youngstown, overlay)", timezone:"America/New_York" },
  "283": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Cincinnati (overlay)", timezone:"America/New_York" },
  "326": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Dayton (overlay)", timezone:"America/New_York" },
  "330": { country:"US", state:"Ohio", stateAbbr:"OH", region:"NE Ohio (Akron, Youngstown, Canton)", timezone:"America/New_York" },
  "380": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Columbus (overlay)", timezone:"America/New_York" },
  "419": { country:"US", state:"Ohio", stateAbbr:"OH", region:"NW Ohio (Toledo, Findlay)", timezone:"America/New_York" },
  "440": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Cleveland W suburbs (Lorain, Elyria)", timezone:"America/New_York" },
  "513": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Cincinnati metro", timezone:"America/New_York" },
  "567": { country:"US", state:"Ohio", stateAbbr:"OH", region:"NW Ohio (overlay)", timezone:"America/New_York" },
  "614": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Columbus metro", timezone:"America/New_York" },
  "740": { country:"US", state:"Ohio", stateAbbr:"OH", region:"SE/Central Ohio (Lancaster, Zanesville, Athens)", timezone:"America/New_York" },
  "937": { country:"US", state:"Ohio", stateAbbr:"OH", region:"Dayton metro", timezone:"America/New_York" },
  // ── Oklahoma ─────────────────────────────────────────────────────────────────
  "405": { country:"US", state:"Oklahoma", stateAbbr:"OK", region:"Central Oklahoma (Oklahoma City metro)", timezone:"America/Chicago" },
  "539": { country:"US", state:"Oklahoma", stateAbbr:"OK", region:"NE Oklahoma (Tulsa, overlay)", timezone:"America/Chicago" },
  "580": { country:"US", state:"Oklahoma", stateAbbr:"OK", region:"S/W Oklahoma (Lawton, Enid, Ardmore)", timezone:"America/Chicago" },
  "918": { country:"US", state:"Oklahoma", stateAbbr:"OK", region:"NE Oklahoma (Tulsa)", timezone:"America/Chicago" },
  // ── Oregon ───────────────────────────────────────────────────────────────────
  "458": { country:"US", state:"Oregon", stateAbbr:"OR", region:"W Oregon (overlay)", timezone:"America/Los_Angeles" },
  "503": { country:"US", state:"Oregon", stateAbbr:"OR", region:"NW Oregon (Portland metro, Salem)", timezone:"America/Los_Angeles" },
  "541": { country:"US", state:"Oregon", stateAbbr:"OR", region:"E/S Oregon (Eugene, Medford, Bend)", timezone:"America/Los_Angeles" },
  "971": { country:"US", state:"Oregon", stateAbbr:"OR", region:"Oregon (overlay)", timezone:"America/Los_Angeles" },
  // ── Pennsylvania ─────────────────────────────────────────────────────────────
  "215": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Philadelphia metro core", timezone:"America/New_York" },
  "223": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Lancaster/Lebanon (overlay)", timezone:"America/New_York" },
  "267": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Philadelphia (overlay)", timezone:"America/New_York" },
  "272": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"NE PA (Scranton, Wilkes-Barre, overlay)", timezone:"America/New_York" },
  "412": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Pittsburgh metro core", timezone:"America/New_York" },
  "445": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Philadelphia (overlay)", timezone:"America/New_York" },
  "484": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Philadelphia W suburbs (Chester, Delaware County)", timezone:"America/New_York" },
  "570": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"NE/N-Central PA (Scranton, Wilkes-Barre)", timezone:"America/New_York" },
  "610": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Philadelphia W suburbs (Allentown, Reading)", timezone:"America/New_York" },
  "717": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"S-Central PA (Harrisburg, Lancaster, York)", timezone:"America/New_York" },
  "724": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"W PA (Pittsburgh area suburbs)", timezone:"America/New_York" },
  "814": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Central/N PA (Erie, State College, Altoona)", timezone:"America/New_York" },
  "878": { country:"US", state:"Pennsylvania", stateAbbr:"PA", region:"Pittsburgh (overlay)", timezone:"America/New_York" },
  // ── Rhode Island ─────────────────────────────────────────────────────────────
  "401": { country:"US", state:"Rhode Island", stateAbbr:"RI", region:"Statewide (Providence, Warwick)", timezone:"America/New_York" },
  // ── South Carolina ───────────────────────────────────────────────────────────
  "803": { country:"US", state:"South Carolina", stateAbbr:"SC", region:"Central SC (Columbia, Aiken)", timezone:"America/New_York" },
  "839": { country:"US", state:"South Carolina", stateAbbr:"SC", region:"South Carolina (overlay)", timezone:"America/New_York" },
  "843": { country:"US", state:"South Carolina", stateAbbr:"SC", region:"Coastal SC (Charleston, Myrtle Beach)", timezone:"America/New_York" },
  "854": { country:"US", state:"South Carolina", stateAbbr:"SC", region:"South Carolina (overlay)", timezone:"America/New_York" },
  "864": { country:"US", state:"South Carolina", stateAbbr:"SC", region:"Upstate SC (Greenville, Spartanburg)", timezone:"America/New_York" },
  // ── South Dakota ─────────────────────────────────────────────────────────────
  "605": { country:"US", state:"South Dakota", stateAbbr:"SD", region:"Statewide (Sioux Falls, Rapid City)", timezone:"America/Chicago" },
  // ── Tennessee ────────────────────────────────────────────────────────────────
  "423": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"E Tennessee (Chattanooga, Kingsport)", timezone:"America/New_York" },
  "615": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"Nashville metro", timezone:"America/Chicago" },
  "629": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"Nashville (overlay)", timezone:"America/Chicago" },
  "731": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"W Tennessee (Jackson, Dyersburg)", timezone:"America/Chicago" },
  "865": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"E Tennessee (Knoxville, Oak Ridge)", timezone:"America/New_York" },
  "901": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"Memphis metro", timezone:"America/Chicago" },
  "931": { country:"US", state:"Tennessee", stateAbbr:"TN", region:"Middle Tennessee (Clarksville, Cookeville)", timezone:"America/Chicago" },
  // ── Texas ────────────────────────────────────────────────────────────────────
  "210": { country:"US", state:"Texas", stateAbbr:"TX", region:"San Antonio metro", timezone:"America/Chicago" },
  "214": { country:"US", state:"Texas", stateAbbr:"TX", region:"Dallas metro core", timezone:"America/Chicago" },
  "254": { country:"US", state:"Texas", stateAbbr:"TX", region:"Central Texas (Waco, Killeen, Temple)", timezone:"America/Chicago" },
  "281": { country:"US", state:"Texas", stateAbbr:"TX", region:"Houston outer suburbs", timezone:"America/Chicago" },
  "325": { country:"US", state:"Texas", stateAbbr:"TX", region:"W-Central Texas (Abilene, San Angelo)", timezone:"America/Chicago" },
  "346": { country:"US", state:"Texas", stateAbbr:"TX", region:"Houston (overlay)", timezone:"America/Chicago" },
  "361": { country:"US", state:"Texas", stateAbbr:"TX", region:"S Coastal Texas (Corpus Christi, Victoria)", timezone:"America/Chicago" },
  "409": { country:"US", state:"Texas", stateAbbr:"TX", region:"SE Texas (Beaumont, Galveston)", timezone:"America/Chicago" },
  "430": { country:"US", state:"Texas", stateAbbr:"TX", region:"NE Texas (Tyler, Texarkana, overlay)", timezone:"America/Chicago" },
  "432": { country:"US", state:"Texas", stateAbbr:"TX", region:"W Texas (Midland, Odessa)", timezone:"America/Denver" },
  "469": { country:"US", state:"Texas", stateAbbr:"TX", region:"Dallas (overlay)", timezone:"America/Chicago" },
  "512": { country:"US", state:"Texas", stateAbbr:"TX", region:"Austin metro", timezone:"America/Chicago" },
  "682": { country:"US", state:"Texas", stateAbbr:"TX", region:"Fort Worth (overlay)", timezone:"America/Chicago" },
  "713": { country:"US", state:"Texas", stateAbbr:"TX", region:"Houston metro core", timezone:"America/Chicago" },
  "726": { country:"US", state:"Texas", stateAbbr:"TX", region:"San Antonio (overlay)", timezone:"America/Chicago" },
  "737": { country:"US", state:"Texas", stateAbbr:"TX", region:"Austin (overlay)", timezone:"America/Chicago" },
  "806": { country:"US", state:"Texas", stateAbbr:"TX", region:"Texas Panhandle (Amarillo, Lubbock)", timezone:"America/Chicago" },
  "817": { country:"US", state:"Texas", stateAbbr:"TX", region:"Fort Worth metro", timezone:"America/Chicago" },
  "830": { country:"US", state:"Texas", stateAbbr:"TX", region:"Hill Country / S Texas (New Braunfels, Del Rio)", timezone:"America/Chicago" },
  "832": { country:"US", state:"Texas", stateAbbr:"TX", region:"Houston (overlay)", timezone:"America/Chicago" },
  "903": { country:"US", state:"Texas", stateAbbr:"TX", region:"E Texas (Tyler, Longview, Texarkana)", timezone:"America/Chicago" },
  "915": { country:"US", state:"Texas", stateAbbr:"TX", region:"El Paso", timezone:"America/Denver" },
  "936": { country:"US", state:"Texas", stateAbbr:"TX", region:"E Texas (Lufkin, Nacogdoches, Huntsville)", timezone:"America/Chicago" },
  "940": { country:"US", state:"Texas", stateAbbr:"TX", region:"N Texas (Wichita Falls, Denton)", timezone:"America/Chicago" },
  "945": { country:"US", state:"Texas", stateAbbr:"TX", region:"Dallas (overlay)", timezone:"America/Chicago" },
  "956": { country:"US", state:"Texas", stateAbbr:"TX", region:"Rio Grande Valley (Laredo, McAllen, Brownsville)", timezone:"America/Chicago" },
  "972": { country:"US", state:"Texas", stateAbbr:"TX", region:"Dallas suburbs (Irving, Garland, Plano)", timezone:"America/Chicago" },
  "979": { country:"US", state:"Texas", stateAbbr:"TX", region:"SE Texas (College Station, Bryan)", timezone:"America/Chicago" },
  // ── Utah ─────────────────────────────────────────────────────────────────────
  "385": { country:"US", state:"Utah", stateAbbr:"UT", region:"Utah (overlay)", timezone:"America/Denver" },
  "435": { country:"US", state:"Utah", stateAbbr:"UT", region:"S/Rural Utah (St. George, Moab, Cedar City)", timezone:"America/Denver" },
  "801": { country:"US", state:"Utah", stateAbbr:"UT", region:"Salt Lake City / Wasatch Front", timezone:"America/Denver" },
  // ── Vermont ──────────────────────────────────────────────────────────────────
  "802": { country:"US", state:"Vermont", stateAbbr:"VT", region:"Statewide (Burlington, Montpelier)", timezone:"America/New_York" },
  // ── Virginia ─────────────────────────────────────────────────────────────────
  "276": { country:"US", state:"Virginia", stateAbbr:"VA", region:"SW Virginia (Bristol, Martinsville)", timezone:"America/New_York" },
  "434": { country:"US", state:"Virginia", stateAbbr:"VA", region:"Central Virginia (Charlottesville, Lynchburg)", timezone:"America/New_York" },
  "540": { country:"US", state:"Virginia", stateAbbr:"VA", region:"N/W Virginia (Roanoke, Winchester, Fredericksburg)", timezone:"America/New_York" },
  "571": { country:"US", state:"Virginia", stateAbbr:"VA", region:"N Virginia (Arlington, Alexandria, Fairfax, overlay)", timezone:"America/New_York" },
  "703": { country:"US", state:"Virginia", stateAbbr:"VA", region:"N Virginia (Arlington, Alexandria, Fairfax)", timezone:"America/New_York" },
  "757": { country:"US", state:"Virginia", stateAbbr:"VA", region:"Hampton Roads (Norfolk, Virginia Beach, Newport News)", timezone:"America/New_York" },
  "804": { country:"US", state:"Virginia", stateAbbr:"VA", region:"Richmond metro", timezone:"America/New_York" },
  // ── Washington ───────────────────────────────────────────────────────────────
  "206": { country:"US", state:"Washington", stateAbbr:"WA", region:"Seattle metro core", timezone:"America/Los_Angeles" },
  "253": { country:"US", state:"Washington", stateAbbr:"WA", region:"S Puget Sound (Tacoma, Federal Way)", timezone:"America/Los_Angeles" },
  "360": { country:"US", state:"Washington", stateAbbr:"WA", region:"W WA outside Seattle (Bellingham, Olympia, Vancouver)", timezone:"America/Los_Angeles" },
  "425": { country:"US", state:"Washington", stateAbbr:"WA", region:"E King County (Bellevue, Kirkland, Redmond)", timezone:"America/Los_Angeles" },
  "509": { country:"US", state:"Washington", stateAbbr:"WA", region:"E Washington (Spokane, Tri-Cities, Yakima)", timezone:"America/Los_Angeles" },
  "564": { country:"US", state:"Washington", stateAbbr:"WA", region:"W Washington (overlay)", timezone:"America/Los_Angeles" },
  // ── West Virginia ────────────────────────────────────────────────────────────
  "304": { country:"US", state:"West Virginia", stateAbbr:"WV", region:"Statewide (Charleston, Huntington, Morgantown)", timezone:"America/New_York" },
  "681": { country:"US", state:"West Virginia", stateAbbr:"WV", region:"Statewide (overlay)", timezone:"America/New_York" },
  // ── Wisconsin ────────────────────────────────────────────────────────────────
  "262": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"SE Wisconsin (Racine, Kenosha, Waukesha)", timezone:"America/Chicago" },
  "414": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"Milwaukee metro", timezone:"America/Chicago" },
  "534": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"NW Wisconsin (overlay)", timezone:"America/Chicago" },
  "608": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"S/W Wisconsin (Madison, La Crosse)", timezone:"America/Chicago" },
  "715": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"N/W Wisconsin (Wausau, Eau Claire, Superior)", timezone:"America/Chicago" },
  "920": { country:"US", state:"Wisconsin", stateAbbr:"WI", region:"NE Wisconsin (Green Bay, Appleton, Oshkosh)", timezone:"America/Chicago" },
  // ── Wyoming ──────────────────────────────────────────────────────────────────
  "307": { country:"US", state:"Wyoming", stateAbbr:"WY", region:"Statewide (Cheyenne, Casper)", timezone:"America/Denver" },
  // ── US Territories ───────────────────────────────────────────────────────────
  "340": { country:"US", state:"U.S. Virgin Islands", stateAbbr:"VI", region:"St. Thomas / St. Croix / St. John", timezone:"America/St_Thomas" },
  "670": { country:"US", state:"N. Mariana Islands", stateAbbr:"MP", region:"Saipan / CNMI", timezone:"Pacific/Saipan" },
  "671": { country:"US", state:"Guam", stateAbbr:"GU", region:"Guam", timezone:"Pacific/Guam" },
  "684": { country:"US", state:"American Samoa", stateAbbr:"AS", region:"American Samoa", timezone:"Pacific/Pago_Pago" },
  "787": { country:"US", state:"Puerto Rico", stateAbbr:"PR", region:"San Juan / Puerto Rico metro", timezone:"America/Puerto_Rico" },
  "939": { country:"US", state:"Puerto Rico", stateAbbr:"PR", region:"Puerto Rico (overlay)", timezone:"America/Puerto_Rico" },

  // ── CANADA ───────────────────────────────────────────────────────────────────
  // Alberta
  "403": { country:"CA", state:"Alberta", stateAbbr:"AB", region:"S Alberta (Calgary, Lethbridge, Medicine Hat)", timezone:"America/Edmonton" },
  "587": { country:"CA", state:"Alberta", stateAbbr:"AB", region:"Alberta (overlay)", timezone:"America/Edmonton" },
  "780": { country:"CA", state:"Alberta", stateAbbr:"AB", region:"N Alberta (Edmonton, Fort McMurray)", timezone:"America/Edmonton" },
  "825": { country:"CA", state:"Alberta", stateAbbr:"AB", region:"Alberta (overlay)", timezone:"America/Edmonton" },
  // British Columbia
  "236": { country:"CA", state:"British Columbia", stateAbbr:"BC", region:"BC (overlay)", timezone:"America/Vancouver" },
  "250": { country:"CA", state:"British Columbia", stateAbbr:"BC", region:"BC outside Vancouver (Victoria, Kelowna, Prince George)", timezone:"America/Vancouver" },
  "604": { country:"CA", state:"British Columbia", stateAbbr:"BC", region:"Metro Vancouver", timezone:"America/Vancouver" },
  "672": { country:"CA", state:"British Columbia", stateAbbr:"BC", region:"BC (overlay)", timezone:"America/Vancouver" },
  "778": { country:"CA", state:"British Columbia", stateAbbr:"BC", region:"BC (overlay)", timezone:"America/Vancouver" },
  // Manitoba
  "204": { country:"CA", state:"Manitoba", stateAbbr:"MB", region:"Winnipeg metro", timezone:"America/Winnipeg" },
  "431": { country:"CA", state:"Manitoba", stateAbbr:"MB", region:"Manitoba (overlay)", timezone:"America/Winnipeg" },
  // New Brunswick
  "506": { country:"CA", state:"New Brunswick", stateAbbr:"NB", region:"New Brunswick (Fredericton, Moncton, Saint John)", timezone:"America/Moncton" },
  // Newfoundland & Labrador
  "709": { country:"CA", state:"Newfoundland & Labrador", stateAbbr:"NL", region:"Newfoundland & Labrador (St. John's)", timezone:"America/St_Johns" },
  // Nova Scotia / PEI
  "782": { country:"CA", state:"Nova Scotia / PEI", stateAbbr:"NS", region:"Nova Scotia & PEI (overlay)", timezone:"America/Halifax" },
  "902": { country:"CA", state:"Nova Scotia / PEI", stateAbbr:"NS", region:"Nova Scotia & PEI (Halifax, Charlottetown)", timezone:"America/Halifax" },
  // Ontario
  "226": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"SW Ontario (Windsor, Kitchener-Waterloo, London)", timezone:"America/Toronto" },
  "249": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"N Ontario (Sudbury, Sault Ste. Marie, overlay)", timezone:"America/Toronto" },
  "289": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"S Ontario (Hamilton, Oakville, St. Catharines, overlay)", timezone:"America/Toronto" },
  "343": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"E Ontario (Ottawa area, overlay)", timezone:"America/Toronto" },
  "365": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"S Ontario (overlay)", timezone:"America/Toronto" },
  "416": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"Toronto core", timezone:"America/Toronto" },
  "437": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"Toronto (overlay)", timezone:"America/Toronto" },
  "519": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"SW Ontario (London, Windsor, Kitchener)", timezone:"America/Toronto" },
  "548": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"SW Ontario (overlay)", timezone:"America/Toronto" },
  "613": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"E Ontario (Ottawa)", timezone:"America/Toronto" },
  "647": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"Toronto (overlay)", timezone:"America/Toronto" },
  "705": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"N Ontario (Sudbury, North Bay, Barrie)", timezone:"America/Toronto" },
  "807": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"NW Ontario (Thunder Bay)", timezone:"America/Toronto" },
  "905": { country:"CA", state:"Ontario", stateAbbr:"ON", region:"Golden Horseshoe (Mississauga, Hamilton, Oshawa, Brampton)", timezone:"America/Toronto" },
  // Quebec
  "354": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Quebec (overlay)", timezone:"America/Toronto" },
  "367": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Quebec City (overlay)", timezone:"America/Toronto" },
  "418": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Quebec City area", timezone:"America/Toronto" },
  "438": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Montreal (overlay)", timezone:"America/Toronto" },
  "450": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"S shore Montreal / Laval / Longueuil", timezone:"America/Toronto" },
  "514": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Montreal core", timezone:"America/Toronto" },
  "579": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"S shore Montreal (overlay)", timezone:"America/Toronto" },
  "581": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"Quebec City (overlay)", timezone:"America/Toronto" },
  "819": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"W Quebec / Gatineau (Outaouais)", timezone:"America/Toronto" },
  "873": { country:"CA", state:"Quebec", stateAbbr:"QC", region:"W Quebec (overlay)", timezone:"America/Toronto" },
  // Saskatchewan
  "306": { country:"CA", state:"Saskatchewan", stateAbbr:"SK", region:"Saskatchewan (Regina, Saskatoon)", timezone:"America/Regina" },
  "639": { country:"CA", state:"Saskatchewan", stateAbbr:"SK", region:"Saskatchewan (overlay)", timezone:"America/Regina" },
  // Yukon / NWT / Nunavut
  "867": { country:"CA", state:"Yukon / NWT / Nunavut", stateAbbr:"YT", region:"Yukon, Northwest Territories, Nunavut", timezone:"America/Whitehorse" },

  // ── CARIBBEAN NANP ───────────────────────────────────────────────────────────
  "242": { country:"NANP", state:"Bahamas", stateAbbr:"BS", region:"Nassau / Bahamas", timezone:"America/Nassau" },
  "246": { country:"NANP", state:"Barbados", stateAbbr:"BB", region:"Barbados", timezone:"America/Barbados" },
  "264": { country:"NANP", state:"Anguilla", stateAbbr:"AI", region:"Anguilla", timezone:"America/Anguilla" },
  "268": { country:"NANP", state:"Antigua and Barbuda", stateAbbr:"AG", region:"Antigua and Barbuda", timezone:"America/Antigua" },
  "284": { country:"NANP", state:"British Virgin Islands", stateAbbr:"VG", region:"British Virgin Islands", timezone:"America/Tortola" },
  "345": { country:"NANP", state:"Cayman Islands", stateAbbr:"KY", region:"Cayman Islands", timezone:"America/Cayman" },
  "441": { country:"NANP", state:"Bermuda", stateAbbr:"BM", region:"Bermuda", timezone:"Atlantic/Bermuda" },
  "473": { country:"NANP", state:"Grenada", stateAbbr:"GD", region:"Grenada", timezone:"America/Grenada" },
  "649": { country:"NANP", state:"Turks and Caicos", stateAbbr:"TC", region:"Turks and Caicos Islands", timezone:"America/Grand_Turk" },
  "664": { country:"NANP", state:"Montserrat", stateAbbr:"MS", region:"Montserrat", timezone:"America/Montserrat" },
  "721": { country:"NANP", state:"Sint Maarten", stateAbbr:"SX", region:"Sint Maarten", timezone:"America/Lower_Princes" },
  "758": { country:"NANP", state:"St. Lucia", stateAbbr:"LC", region:"Saint Lucia", timezone:"America/St_Lucia" },
  "767": { country:"NANP", state:"Dominica", stateAbbr:"DM", region:"Dominica", timezone:"America/Dominica" },
  "784": { country:"NANP", state:"St. Vincent and the Grenadines", stateAbbr:"VC", region:"Saint Vincent and the Grenadines", timezone:"America/St_Vincent" },
  "809": { country:"NANP", state:"Dominican Republic", stateAbbr:"DO", region:"Santo Domingo / S Dominican Republic", timezone:"America/Santo_Domingo" },
  "829": { country:"NANP", state:"Dominican Republic", stateAbbr:"DO", region:"Dominican Republic (overlay)", timezone:"America/Santo_Domingo" },
  "849": { country:"NANP", state:"Dominican Republic", stateAbbr:"DO", region:"Dominican Republic (overlay)", timezone:"America/Santo_Domingo" },
  "868": { country:"NANP", state:"Trinidad and Tobago", stateAbbr:"TT", region:"Trinidad and Tobago", timezone:"America/Port_of_Spain" },
  "869": { country:"NANP", state:"St. Kitts and Nevis", stateAbbr:"KN", region:"Saint Kitts and Nevis", timezone:"America/St_Kitts" },
  "876": { country:"NANP", state:"Jamaica", stateAbbr:"JM", region:"Jamaica", timezone:"America/Jamaica" },
};

export function getNpaInfo(nationalDigits: string): NpaInfo | null {
  if (nationalDigits.length < 3) return null;
  const npa = nationalDigits.slice(0, 3);
  return NPA_DATABASE[npa] ?? null;
}
