"use client";

import { useState } from "react";
import { FileText, Download } from "lucide-react";
import type { LookupResponse } from "@/lib/types";

interface Props {
  data: LookupResponse;
}

function val(v: unknown): string {
  if (v === null || v === undefined) return "N/A";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  if (Array.isArray(v)) return v.join(", ") || "N/A";
  return String(v);
}

function generateTextReport(data: LookupResponse): string {
  const { input, aggregated, analysis, sources } = data;
  const now = new Date().toISOString();
  const separator = "─".repeat(70);

  const sourceStatus = [
    `  libphonenumber-js : ACTIVE (offline, always available)`,
    `  NumVerify         : ${sources.numverify.ok ? "ACTIVE" : sources.numverify.error === "NOT_CONFIGURED" ? "NOT CONFIGURED" : `ERROR — ${sources.numverify.error}`}`,
    `  IPQualityScore    : ${sources.ipqs.ok ? "ACTIVE" : sources.ipqs.error === "NOT_CONFIGURED" ? "NOT CONFIGURED" : `ERROR — ${sources.ipqs.error}`}`,
    `  AbstractAPI       : ${sources.abstract.ok ? "ACTIVE" : sources.abstract.error === "NOT_CONFIGURED" ? "NOT CONFIGURED" : `ERROR — ${sources.abstract.error}`}`,
    `  Twilio Lookup     : ${sources.twilio.ok ? "ACTIVE" : sources.twilio.error === "NOT_CONFIGURED" ? "NOT CONFIGURED" : `ERROR — ${sources.twilio.error}`}`,
  ].join("\n");

  const npa = analysis.npaInfo;

  const lines = [
    `HEAVEN-GeoIntel — Phone Intelligence Report`,
    `Generated  : ${now}`,
    separator,
    ``,
    `TARGET NUMBER`,
    separator,
    `  E.164 (canonical)  : ${input.e164}`,
    `  International      : ${aggregated.formatInternational}`,
    `  National           : ${aggregated.formatNational}`,
    `  RFC 3966           : ${aggregated.formatRfc3966}`,
    `  Valid              : ${val(input.isValid)}`,
    `  Possible           : ${val(input.isPossible)}`,
    ``,
    `GEOGRAPHIC INTELLIGENCE`,
    separator,
    `  Country            : ${aggregated.countryName} (${aggregated.country})`,
    `  Calling Code       : ${input.countryCallingCode}`,
    ...(npa ? [
      `  State / Province   : ${npa.state} (${npa.stateAbbr})`,
      `  Region / Metro     : ${npa.region}`,
      `  Area Code (NPA)    : ${analysis.nationalNumber.slice(0, 3)}`,
      `  Timezone (NPA DB)  : ${npa.timezone}`,
    ] : []),
    `  Timezone (IANA)    : ${val(aggregated.timezone)}`,
    `  UTC Offset         : ${val(aggregated.utcOffsets)}`,
    `  Region (API)       : ${val(aggregated.region)}`,
    `  City (API)         : ${val(aggregated.city)}`,
    ``,
    `NUMBER CLASSIFICATION`,
    separator,
    `  Line Type          : ${val(aggregated.lineType)}`,
    `  Type Description   : ${val(aggregated.typeDescription)}`,
    `  Ambiguous Type     : ${val(aggregated.isAmbiguousType)} ${aggregated.isAmbiguousType ? "(mobile/landline unresolvable from number structure)" : ""}`,
    `  Confirmed Mobile   : ${val(aggregated.isMobile)}`,
    `  Confirmed Fixed    : ${val(aggregated.isFixedLine)}`,
    `  VoIP               : ${val(aggregated.isVoip)}`,
    `  Toll-Free          : ${val(analysis.isTollFree)}`,
    `  Premium Rate       : ${val(analysis.isPremiumRate)}`,
    ``,
    `CARRIER / NETWORK`,
    separator,
    `  Carrier            : ${val(aggregated.carrier)}`,
    `  Prepaid            : ${val(aggregated.prepaid)}`,
    `  Line Active        : ${val(aggregated.active)}`,
    `  Active Status      : ${val(aggregated.activeStatus)}`,
    `  User Activity      : ${val(aggregated.userActivity)}`,
    `  MCC / MNC          : ${aggregated.mobileCountryCode && aggregated.mobileNetworkCode ? `${aggregated.mobileCountryCode} / ${aggregated.mobileNetworkCode}` : "N/A"}`,
    ``,
    `CALLER IDENTITY`,
    separator,
    `  Owner / CNAM       : ${val(aggregated.callerName)}`,
    `  Caller Type        : ${val(aggregated.callerType)}`,
    `  Associated Emails  : ${val(aggregated.associatedEmails)}`,
    ``,
    `RISK INTELLIGENCE`,
    separator,
    `  Fraud Score        : ${aggregated.fraudScore !== null ? `${aggregated.fraudScore}/100` : "N/A"}`,
    `  High Risk          : ${val(aggregated.isRisky)}`,
    `  Recent Abuse       : ${val(aggregated.recentAbuse)}`,
    `  VoIP               : ${val(aggregated.isVoip)}`,
    `  Disposable         : ${val(aggregated.isDisposable)}`,
    ``,
    `NUMBER STRUCTURE`,
    separator,
    `  Area Code          : ${val(analysis.areaCode)}`,
    `  Subscriber         : ${val(analysis.subscriberNumber)}`,
    `  Carrier Prefix     : ${val(aggregated.carrierPrefix)}`,
    `  Digit Count        : ${val(aggregated.numberLength)}`,
    `  Expected Length    : ${analysis.expectedLengths.length > 0 ? analysis.expectedLengths.join(" or ") : "N/A"}`,
    ``,
    `DATA SOURCES`,
    separator,
    sourceStatus,
    ``,
    separator,
    `Report generated by HEAVEN-GeoIntel — for authorized use only.`,
    `All intelligence should be verified before use in assessments.`,
  ];

  return lines.join("\n");
}

function generateHtmlReport(data: LookupResponse): string {
  const text = generateTextReport(data);
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HEAVEN-GeoIntel Report — ${data.input.e164}</title>
<style>
  body { background: #0a0a0a; color: #00ff41; font-family: 'Courier New', monospace; padding: 40px; max-width: 900px; margin: 0 auto; }
  pre { white-space: pre-wrap; word-break: break-word; font-size: 13px; line-height: 1.7; }
  h1 { color: #00ff41; border-bottom: 1px solid #00ff4130; padding-bottom: 8px; font-size: 16px; letter-spacing: 4px; text-transform: uppercase; }
</style>
</head>
<body>
<h1>HEAVEN-GeoIntel — Intelligence Report</h1>
<pre>${escaped}</pre>
</body>
</html>`;
}

export default function ReportExport({ data }: Props) {
  const [exported, setExported] = useState<"text" | "html" | null>(null);

  const downloadText = () => {
    const content = generateTextReport(data);
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `geointel_${data.input.e164.replace(/\D/g, "")}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setExported("text");
    setTimeout(() => setExported(null), 2000);
  };

  const downloadHtml = () => {
    const content = generateHtmlReport(data);
    const blob = new Blob([content], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `geointel_${data.input.e164.replace(/\D/g, "")}_${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
    setExported("html");
    setTimeout(() => setExported(null), 2000);
  };

  return (
    <div className="flex items-center gap-2 flex-wrap">
      <button
        onClick={downloadText}
        className="flex items-center gap-1.5 text-xs border border-[#00ff41]/30 px-3 py-1.5 text-[#00ff41]/70 hover:text-[#00ff41] hover:border-[#00ff41]/60 transition-colors font-mono"
      >
        <FileText className="w-3 h-3" />
        {exported === "text" ? "SAVED" : "EXPORT TXT REPORT"}
      </button>
      <button
        onClick={downloadHtml}
        className="flex items-center gap-1.5 text-xs border border-[#00d9ff]/30 px-3 py-1.5 text-[#00d9ff]/70 hover:text-[#00d9ff] hover:border-[#00d9ff]/60 transition-colors font-mono"
      >
        <Download className="w-3 h-3" />
        {exported === "html" ? "SAVED" : "EXPORT HTML REPORT"}
      </button>
    </div>
  );
}
