// Bundled country intelligence — zero API calls, fully offline
export interface CountryIntel {
  code: string;
  name: string;
  officialName: string;
  capital: string;
  region: string;
  subregion: string;
  continent: string;
  population: number;
  area: number; // km²
  currency: { code: string; name: string; symbol: string };
  languages: string[];
  callingCode: string;
  tld: string[];
  flagEmoji: string;
  drivingSide: "left" | "right";
  timezones: string[];
  emergencyNumber: string;
  internetUsers: string; // percentage
  gdpPerCapita: string;
}

// Comprehensive dataset for 50+ major countries + all regions
const COUNTRY_DATA: Record<string, CountryIntel> = {
  US: {
    code: "US", name: "United States", officialName: "United States of America",
    capital: "Washington, D.C.", region: "Americas", subregion: "Northern America", continent: "North America",
    population: 331000000, area: 9833517,
    currency: { code: "USD", name: "US Dollar", symbol: "$" },
    languages: ["English"], callingCode: "+1", tld: [".us", ".gov", ".edu", ".mil"],
    flagEmoji: "🇺🇸", drivingSide: "right",
    timezones: ["UTC-5 (ET)", "UTC-6 (CT)", "UTC-7 (MT)", "UTC-8 (PT)"],
    emergencyNumber: "911", internetUsers: "91%", gdpPerCapita: "$65,000",
  },
  GB: {
    code: "GB", name: "United Kingdom", officialName: "United Kingdom of Great Britain and Northern Ireland",
    capital: "London", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 67000000, area: 242495,
    currency: { code: "GBP", name: "British Pound", symbol: "£" },
    languages: ["English"], callingCode: "+44", tld: [".uk", ".co.uk"],
    flagEmoji: "🇬🇧", drivingSide: "left",
    timezones: ["UTC+0 (GMT)", "UTC+1 (BST)"],
    emergencyNumber: "999", internetUsers: "95%", gdpPerCapita: "$46,000",
  },
  DE: {
    code: "DE", name: "Germany", officialName: "Federal Republic of Germany",
    capital: "Berlin", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 83000000, area: 357114,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["German"], callingCode: "+49", tld: [".de"],
    flagEmoji: "🇩🇪", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "89%", gdpPerCapita: "$51,000",
  },
  FR: {
    code: "FR", name: "France", officialName: "French Republic",
    capital: "Paris", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 67500000, area: 551695,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["French"], callingCode: "+33", tld: [".fr"],
    flagEmoji: "🇫🇷", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "87%", gdpPerCapita: "$43,000",
  },
  IN: {
    code: "IN", name: "India", officialName: "Republic of India",
    capital: "New Delhi", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 1393000000, area: 3287263,
    currency: { code: "INR", name: "Indian Rupee", symbol: "₹" },
    languages: ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil"],
    callingCode: "+91", tld: [".in"],
    flagEmoji: "🇮🇳", drivingSide: "left",
    timezones: ["UTC+5:30 (IST)"],
    emergencyNumber: "112", internetUsers: "54%", gdpPerCapita: "$2,100",
  },
  CN: {
    code: "CN", name: "China", officialName: "People's Republic of China",
    capital: "Beijing", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 1412000000, area: 9596960,
    currency: { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    languages: ["Mandarin Chinese"], callingCode: "+86", tld: [".cn"],
    flagEmoji: "🇨🇳", drivingSide: "right",
    timezones: ["UTC+8 (CST)"],
    emergencyNumber: "110", internetUsers: "73%", gdpPerCapita: "$12,000",
  },
  JP: {
    code: "JP", name: "Japan", officialName: "Japan",
    capital: "Tokyo", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 125700000, area: 377930,
    currency: { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    languages: ["Japanese"], callingCode: "+81", tld: [".jp"],
    flagEmoji: "🇯🇵", drivingSide: "left",
    timezones: ["UTC+9 (JST)"],
    emergencyNumber: "110", internetUsers: "93%", gdpPerCapita: "$40,000",
  },
  BR: {
    code: "BR", name: "Brazil", officialName: "Federative Republic of Brazil",
    capital: "Brasília", region: "Americas", subregion: "South America", continent: "South America",
    population: 213000000, area: 8515767,
    currency: { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    languages: ["Portuguese"], callingCode: "+55", tld: [".br"],
    flagEmoji: "🇧🇷", drivingSide: "right",
    timezones: ["UTC-3 (BRT)", "UTC-4 (AMT)", "UTC-5 (ACT)"],
    emergencyNumber: "190", internetUsers: "81%", gdpPerCapita: "$8,700",
  },
  RU: {
    code: "RU", name: "Russia", officialName: "Russian Federation",
    capital: "Moscow", region: "Europe", subregion: "Eastern Europe", continent: "Europe/Asia",
    population: 144000000, area: 17098242,
    currency: { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    languages: ["Russian"], callingCode: "+7", tld: [".ru"],
    flagEmoji: "🇷🇺", drivingSide: "right",
    timezones: ["UTC+2 to UTC+12"],
    emergencyNumber: "112", internetUsers: "85%", gdpPerCapita: "$12,000",
  },
  CA: {
    code: "CA", name: "Canada", officialName: "Canada",
    capital: "Ottawa", region: "Americas", subregion: "Northern America", continent: "North America",
    population: 37000000, area: 9984670,
    currency: { code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
    languages: ["English", "French"], callingCode: "+1", tld: [".ca"],
    flagEmoji: "🇨🇦", drivingSide: "right",
    timezones: ["UTC-3:30 (NST)", "UTC-4 (AST)", "UTC-5 (EST)", "UTC-6 (CST)", "UTC-7 (MST)", "UTC-8 (PST)"],
    emergencyNumber: "911", internetUsers: "94%", gdpPerCapita: "$50,000",
  },
  AU: {
    code: "AU", name: "Australia", officialName: "Commonwealth of Australia",
    capital: "Canberra", region: "Oceania", subregion: "Australia and New Zealand", continent: "Oceania",
    population: 25700000, area: 7692024,
    currency: { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    languages: ["English"], callingCode: "+61", tld: [".au"],
    flagEmoji: "🇦🇺", drivingSide: "left",
    timezones: ["UTC+8 (AWST)", "UTC+9:30 (ACST)", "UTC+10 (AEST)", "UTC+10:30 (ACDT)"],
    emergencyNumber: "000", internetUsers: "87%", gdpPerCapita: "$55,000",
  },
  MX: {
    code: "MX", name: "Mexico", officialName: "United Mexican States",
    capital: "Mexico City", region: "Americas", subregion: "Central America", continent: "North America",
    population: 128000000, area: 1964375,
    currency: { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
    languages: ["Spanish"], callingCode: "+52", tld: [".mx"],
    flagEmoji: "🇲🇽", drivingSide: "right",
    timezones: ["UTC-6 (CST)", "UTC-7 (MST)", "UTC-8 (PST)"],
    emergencyNumber: "911", internetUsers: "72%", gdpPerCapita: "$10,000",
  },
  KR: {
    code: "KR", name: "South Korea", officialName: "Republic of Korea",
    capital: "Seoul", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 51000000, area: 100210,
    currency: { code: "KRW", name: "South Korean Won", symbol: "₩" },
    languages: ["Korean"], callingCode: "+82", tld: [".kr"],
    flagEmoji: "🇰🇷", drivingSide: "right",
    timezones: ["UTC+9 (KST)"],
    emergencyNumber: "112", internetUsers: "97%", gdpPerCapita: "$33,000",
  },
  IT: {
    code: "IT", name: "Italy", officialName: "Italian Republic",
    capital: "Rome", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 59000000, area: 301340,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Italian"], callingCode: "+39", tld: [".it"],
    flagEmoji: "🇮🇹", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "75%", gdpPerCapita: "$34,000",
  },
  ES: {
    code: "ES", name: "Spain", officialName: "Kingdom of Spain",
    capital: "Madrid", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 46700000, area: 505990,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Spanish"], callingCode: "+34", tld: [".es"],
    flagEmoji: "🇪🇸", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "91%", gdpPerCapita: "$29,000",
  },
  NL: {
    code: "NL", name: "Netherlands", officialName: "Kingdom of the Netherlands",
    capital: "Amsterdam", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 17400000, area: 41543,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Dutch"], callingCode: "+31", tld: [".nl"],
    flagEmoji: "🇳🇱", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "95%", gdpPerCapita: "$57,000",
  },
  SA: {
    code: "SA", name: "Saudi Arabia", officialName: "Kingdom of Saudi Arabia",
    capital: "Riyadh", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 34800000, area: 2149690,
    currency: { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    languages: ["Arabic"], callingCode: "+966", tld: [".sa"],
    flagEmoji: "🇸🇦", drivingSide: "right",
    timezones: ["UTC+3 (AST)"],
    emergencyNumber: "911", internetUsers: "95%", gdpPerCapita: "$24,000",
  },
  ZA: {
    code: "ZA", name: "South Africa", officialName: "Republic of South Africa",
    capital: "Pretoria", region: "Africa", subregion: "Southern Africa", continent: "Africa",
    population: 59000000, area: 1219090,
    currency: { code: "ZAR", name: "South African Rand", symbol: "R" },
    languages: ["Zulu", "Xhosa", "Afrikaans", "English"],
    callingCode: "+27", tld: [".za"],
    flagEmoji: "🇿🇦", drivingSide: "left",
    timezones: ["UTC+2 (SAST)"],
    emergencyNumber: "10111", internetUsers: "64%", gdpPerCapita: "$6,800",
  },
  NG: {
    code: "NG", name: "Nigeria", officialName: "Federal Republic of Nigeria",
    capital: "Abuja", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 206000000, area: 923768,
    currency: { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
    callingCode: "+234", tld: [".ng"],
    flagEmoji: "🇳🇬", drivingSide: "right",
    timezones: ["UTC+1 (WAT)"],
    emergencyNumber: "199", internetUsers: "51%", gdpPerCapita: "$2,200",
  },
  EG: {
    code: "EG", name: "Egypt", officialName: "Arab Republic of Egypt",
    capital: "Cairo", region: "Africa", subregion: "Northern Africa", continent: "Africa",
    population: 102000000, area: 1002450,
    currency: { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
    languages: ["Arabic"], callingCode: "+20", tld: [".eg"],
    flagEmoji: "🇪🇬", drivingSide: "right",
    timezones: ["UTC+2 (EET)"],
    emergencyNumber: "122", internetUsers: "72%", gdpPerCapita: "$4,200",
  },
  PK: {
    code: "PK", name: "Pakistan", officialName: "Islamic Republic of Pakistan",
    capital: "Islamabad", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 220000000, area: 881913,
    currency: { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    languages: ["Urdu", "English"], callingCode: "+92", tld: [".pk"],
    flagEmoji: "🇵🇰", drivingSide: "left",
    timezones: ["UTC+5 (PKT)"],
    emergencyNumber: "115", internetUsers: "47%", gdpPerCapita: "$1,600",
  },
  BD: {
    code: "BD", name: "Bangladesh", officialName: "People's Republic of Bangladesh",
    capital: "Dhaka", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 166000000, area: 147570,
    currency: { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    languages: ["Bengali"], callingCode: "+880", tld: [".bd"],
    flagEmoji: "🇧🇩", drivingSide: "left",
    timezones: ["UTC+6 (BST)"],
    emergencyNumber: "999", internetUsers: "39%", gdpPerCapita: "$2,200",
  },
  TR: {
    code: "TR", name: "Turkey", officialName: "Republic of Türkiye",
    capital: "Ankara", region: "Asia", subregion: "Western Asia", continent: "Asia/Europe",
    population: 84300000, area: 783562,
    currency: { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    languages: ["Turkish"], callingCode: "+90", tld: [".tr"],
    flagEmoji: "🇹🇷", drivingSide: "right",
    timezones: ["UTC+3 (TRT)"],
    emergencyNumber: "112", internetUsers: "79%", gdpPerCapita: "$9,600",
  },
  PH: {
    code: "PH", name: "Philippines", officialName: "Republic of the Philippines",
    capital: "Manila", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 110000000, area: 300000,
    currency: { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    languages: ["Filipino", "English"], callingCode: "+63", tld: [".ph"],
    flagEmoji: "🇵🇭", drivingSide: "right",
    timezones: ["UTC+8 (PST)"],
    emergencyNumber: "911", internetUsers: "73%", gdpPerCapita: "$3,500",
  },
  ID: {
    code: "ID", name: "Indonesia", officialName: "Republic of Indonesia",
    capital: "Jakarta", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 273500000, area: 1904569,
    currency: { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    languages: ["Indonesian"], callingCode: "+62", tld: [".id"],
    flagEmoji: "🇮🇩", drivingSide: "left",
    timezones: ["UTC+7 (WIB)", "UTC+8 (WITA)", "UTC+9 (WIT)"],
    emergencyNumber: "112", internetUsers: "62%", gdpPerCapita: "$4,000",
  },
  SE: {
    code: "SE", name: "Sweden", officialName: "Kingdom of Sweden",
    capital: "Stockholm", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 10400000, area: 450295,
    currency: { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    languages: ["Swedish"], callingCode: "+46", tld: [".se"],
    flagEmoji: "🇸🇪", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "95%", gdpPerCapita: "$55,000",
  },
  NO: {
    code: "NO", name: "Norway", officialName: "Kingdom of Norway",
    capital: "Oslo", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 5400000, area: 385207,
    currency: { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    languages: ["Norwegian"], callingCode: "+47", tld: [".no"],
    flagEmoji: "🇳🇴", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "97%", gdpPerCapita: "$82,000",
  },
  CH: {
    code: "CH", name: "Switzerland", officialName: "Swiss Confederation",
    capital: "Bern", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 8700000, area: 41285,
    currency: { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
    languages: ["German", "French", "Italian", "Romansh"], callingCode: "+41", tld: [".ch"],
    flagEmoji: "🇨🇭", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "93%", gdpPerCapita: "$86,000",
  },
  SG: {
    code: "SG", name: "Singapore", officialName: "Republic of Singapore",
    capital: "Singapore", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 5850000, area: 728,
    currency: { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    languages: ["English", "Malay", "Mandarin", "Tamil"], callingCode: "+65", tld: [".sg"],
    flagEmoji: "🇸🇬", drivingSide: "left",
    timezones: ["UTC+8 (SGT)"],
    emergencyNumber: "999", internetUsers: "92%", gdpPerCapita: "$65,000",
  },
  AE: {
    code: "AE", name: "UAE", officialName: "United Arab Emirates",
    capital: "Abu Dhabi", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 9890000, area: 83600,
    currency: { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    languages: ["Arabic"], callingCode: "+971", tld: [".ae"],
    flagEmoji: "🇦🇪", drivingSide: "right",
    timezones: ["UTC+4 (GST)"],
    emergencyNumber: "999", internetUsers: "99%", gdpPerCapita: "$43,000",
  },
  IL: {
    code: "IL", name: "Israel", officialName: "State of Israel",
    capital: "Jerusalem", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 9290000, area: 20770,
    currency: { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
    languages: ["Hebrew", "Arabic"], callingCode: "+972", tld: [".il"],
    flagEmoji: "🇮🇱", drivingSide: "right",
    timezones: ["UTC+2 (IST)", "UTC+3 (IDT)"],
    emergencyNumber: "100", internetUsers: "90%", gdpPerCapita: "$44,000",
  },
  NZ: {
    code: "NZ", name: "New Zealand", officialName: "New Zealand",
    capital: "Wellington", region: "Oceania", subregion: "Australia and New Zealand", continent: "Oceania",
    population: 5000000, area: 270467,
    currency: { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    languages: ["English", "Māori"], callingCode: "+64", tld: [".nz"],
    flagEmoji: "🇳🇿", drivingSide: "left",
    timezones: ["UTC+12 (NZST)", "UTC+13 (NZDT)"],
    emergencyNumber: "111", internetUsers: "91%", gdpPerCapita: "$48,000",
  },
  AR: {
    code: "AR", name: "Argentina", officialName: "Argentine Republic",
    capital: "Buenos Aires", region: "Americas", subregion: "South America", continent: "South America",
    population: 45600000, area: 2780400,
    currency: { code: "ARS", name: "Argentine Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+54", tld: [".ar"],
    flagEmoji: "🇦🇷", drivingSide: "right",
    timezones: ["UTC-3 (ART)"],
    emergencyNumber: "911", internetUsers: "78%", gdpPerCapita: "$9,800",
  },
  PL: {
    code: "PL", name: "Poland", officialName: "Republic of Poland",
    capital: "Warsaw", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 38000000, area: 312679,
    currency: { code: "PLN", name: "Polish Złoty", symbol: "zł" },
    languages: ["Polish"], callingCode: "+48", tld: [".pl"],
    flagEmoji: "🇵🇱", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "86%", gdpPerCapita: "$17,000",
  },
  UA: {
    code: "UA", name: "Ukraine", officialName: "Ukraine",
    capital: "Kyiv", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 43500000, area: 603550,
    currency: { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    languages: ["Ukrainian"], callingCode: "+380", tld: [".ua"],
    flagEmoji: "🇺🇦", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "77%", gdpPerCapita: "$4,800",
  },
  TH: {
    code: "TH", name: "Thailand", officialName: "Kingdom of Thailand",
    capital: "Bangkok", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 70000000, area: 513120,
    currency: { code: "THB", name: "Thai Baht", symbol: "฿" },
    languages: ["Thai"], callingCode: "+66", tld: [".th"],
    flagEmoji: "🇹🇭", drivingSide: "left",
    timezones: ["UTC+7 (ICT)"],
    emergencyNumber: "191", internetUsers: "78%", gdpPerCapita: "$7,800",
  },
  VN: {
    code: "VN", name: "Vietnam", officialName: "Socialist Republic of Vietnam",
    capital: "Hanoi", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 97300000, area: 331212,
    currency: { code: "VND", name: "Vietnamese Đồng", symbol: "₫" },
    languages: ["Vietnamese"], callingCode: "+84", tld: [".vn"],
    flagEmoji: "🇻🇳", drivingSide: "right",
    timezones: ["UTC+7 (ICT)"],
    emergencyNumber: "113", internetUsers: "73%", gdpPerCapita: "$3,500",
  },
  MY: {
    code: "MY", name: "Malaysia", officialName: "Malaysia",
    capital: "Kuala Lumpur", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 32400000, area: 329847,
    currency: { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    languages: ["Malay", "English"], callingCode: "+60", tld: [".my"],
    flagEmoji: "🇲🇾", drivingSide: "left",
    timezones: ["UTC+8 (MYT)"],
    emergencyNumber: "999", internetUsers: "89%", gdpPerCapita: "$12,000",
  },
  IR: {
    code: "IR", name: "Iran", officialName: "Islamic Republic of Iran",
    capital: "Tehran", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 83500000, area: 1648195,
    currency: { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
    languages: ["Persian"], callingCode: "+98", tld: [".ir"],
    flagEmoji: "🇮🇷", drivingSide: "right",
    timezones: ["UTC+3:30 (IRST)", "UTC+4:30 (IRDT)"],
    emergencyNumber: "110", internetUsers: "72%", gdpPerCapita: "$6,000",
  },
  GH: {
    code: "GH", name: "Ghana", officialName: "Republic of Ghana",
    capital: "Accra", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 31000000, area: 238533,
    currency: { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
    languages: ["English"], callingCode: "+233", tld: [".gh"],
    flagEmoji: "🇬🇭", drivingSide: "right",
    timezones: ["UTC+0 (GMT)"],
    emergencyNumber: "999", internetUsers: "58%", gdpPerCapita: "$2,400",
  },
  KE: {
    code: "KE", name: "Kenya", officialName: "Republic of Kenya",
    capital: "Nairobi", region: "Africa", subregion: "Eastern Africa", continent: "Africa",
    population: 53800000, area: 580367,
    currency: { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    languages: ["English", "Swahili"], callingCode: "+254", tld: [".ke"],
    flagEmoji: "🇰🇪", drivingSide: "left",
    timezones: ["UTC+3 (EAT)"],
    emergencyNumber: "999", internetUsers: "40%", gdpPerCapita: "$1,900",
  },
  PT: {
    code: "PT", name: "Portugal", officialName: "Portuguese Republic",
    capital: "Lisbon", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 10300000, area: 92212,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Portuguese"], callingCode: "+351", tld: [".pt"],
    flagEmoji: "🇵🇹", drivingSide: "right",
    timezones: ["UTC+0 (WET)", "UTC+1 (WEST)"],
    emergencyNumber: "112", internetUsers: "80%", gdpPerCapita: "$23,000",
  },
  GR: {
    code: "GR", name: "Greece", officialName: "Hellenic Republic",
    capital: "Athens", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 10700000, area: 131957,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Greek"], callingCode: "+30", tld: [".gr"],
    flagEmoji: "🇬🇷", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "81%", gdpPerCapita: "$19,000",
  },
  CL: {
    code: "CL", name: "Chile", officialName: "Republic of Chile",
    capital: "Santiago", region: "Americas", subregion: "South America", continent: "South America",
    population: 19100000, area: 756102,
    currency: { code: "CLP", name: "Chilean Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+56", tld: [".cl"],
    flagEmoji: "🇨🇱", drivingSide: "right",
    timezones: ["UTC-4 (CLT)", "UTC-3 (CLST)"],
    emergencyNumber: "133", internetUsers: "88%", gdpPerCapita: "$16,000",
  },
};

export function getCountryIntel(code: string): CountryIntel | null {
  return COUNTRY_DATA[code.toUpperCase()] ?? null;
}

export function getCallingCodeToCountry(callingCode: string): string | null {
  const clean = callingCode.replace("+", "");
  for (const [cc, data] of Object.entries(COUNTRY_DATA)) {
    if (data.callingCode === `+${clean}`) return cc;
  }
  return null;
}

export { COUNTRY_DATA };
