// Bundled country intelligence — zero API calls, fully offline
export interface CountryIntel {
  code: string;
  name: string;
  officialName: string;
  capital: string;
  region: string;
  subregion: string;
  continent: string;
  population: number;
  area: number; // km²
  currency: { code: string; name: string; symbol: string };
  languages: string[];
  callingCode: string;
  tld: string[];
  flagEmoji: string;
  drivingSide: "left" | "right";
  timezones: string[];
  emergencyNumber: string;
  internetUsers: string; // percentage
  gdpPerCapita: string;
}

// Comprehensive dataset for 100 countries across all regions
const COUNTRY_DATA: Record<string, CountryIntel> = {
  US: {
    code: "US", name: "United States", officialName: "United States of America",
    capital: "Washington, D.C.", region: "Americas", subregion: "Northern America", continent: "North America",
    population: 331000000, area: 9833517,
    currency: { code: "USD", name: "US Dollar", symbol: "$" },
    languages: ["English"], callingCode: "+1", tld: [".us", ".gov", ".edu", ".mil"],
    flagEmoji: "🇺🇸", drivingSide: "right",
    timezones: ["UTC-5 (ET)", "UTC-6 (CT)", "UTC-7 (MT)", "UTC-8 (PT)"],
    emergencyNumber: "911", internetUsers: "91%", gdpPerCapita: "$65,000",
  },
  GB: {
    code: "GB", name: "United Kingdom", officialName: "United Kingdom of Great Britain and Northern Ireland",
    capital: "London", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 67000000, area: 242495,
    currency: { code: "GBP", name: "British Pound", symbol: "£" },
    languages: ["English"], callingCode: "+44", tld: [".uk", ".co.uk"],
    flagEmoji: "🇬🇧", drivingSide: "left",
    timezones: ["UTC+0 (GMT)", "UTC+1 (BST)"],
    emergencyNumber: "999", internetUsers: "95%", gdpPerCapita: "$46,000",
  },
  DE: {
    code: "DE", name: "Germany", officialName: "Federal Republic of Germany",
    capital: "Berlin", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 83000000, area: 357114,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["German"], callingCode: "+49", tld: [".de"],
    flagEmoji: "🇩🇪", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "89%", gdpPerCapita: "$51,000",
  },
  FR: {
    code: "FR", name: "France", officialName: "French Republic",
    capital: "Paris", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 67500000, area: 551695,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["French"], callingCode: "+33", tld: [".fr"],
    flagEmoji: "🇫🇷", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "87%", gdpPerCapita: "$43,000",
  },
  IN: {
    code: "IN", name: "India", officialName: "Republic of India",
    capital: "New Delhi", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 1393000000, area: 3287263,
    currency: { code: "INR", name: "Indian Rupee", symbol: "₹" },
    languages: ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil"],
    callingCode: "+91", tld: [".in"],
    flagEmoji: "🇮🇳", drivingSide: "left",
    timezones: ["UTC+5:30 (IST)"],
    emergencyNumber: "112", internetUsers: "54%", gdpPerCapita: "$2,100",
  },
  CN: {
    code: "CN", name: "China", officialName: "People's Republic of China",
    capital: "Beijing", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 1412000000, area: 9596960,
    currency: { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
    languages: ["Mandarin Chinese"], callingCode: "+86", tld: [".cn"],
    flagEmoji: "🇨🇳", drivingSide: "right",
    timezones: ["UTC+8 (CST)"],
    emergencyNumber: "110", internetUsers: "73%", gdpPerCapita: "$12,000",
  },
  JP: {
    code: "JP", name: "Japan", officialName: "Japan",
    capital: "Tokyo", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 125700000, area: 377930,
    currency: { code: "JPY", name: "Japanese Yen", symbol: "¥" },
    languages: ["Japanese"], callingCode: "+81", tld: [".jp"],
    flagEmoji: "🇯🇵", drivingSide: "left",
    timezones: ["UTC+9 (JST)"],
    emergencyNumber: "110", internetUsers: "93%", gdpPerCapita: "$40,000",
  },
  BR: {
    code: "BR", name: "Brazil", officialName: "Federative Republic of Brazil",
    capital: "Brasília", region: "Americas", subregion: "South America", continent: "South America",
    population: 213000000, area: 8515767,
    currency: { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    languages: ["Portuguese"], callingCode: "+55", tld: [".br"],
    flagEmoji: "🇧🇷", drivingSide: "right",
    timezones: ["UTC-3 (BRT)", "UTC-4 (AMT)", "UTC-5 (ACT)"],
    emergencyNumber: "190", internetUsers: "81%", gdpPerCapita: "$8,700",
  },
  RU: {
    code: "RU", name: "Russia", officialName: "Russian Federation",
    capital: "Moscow", region: "Europe", subregion: "Eastern Europe", continent: "Europe/Asia",
    population: 144000000, area: 17098242,
    currency: { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    languages: ["Russian"], callingCode: "+7", tld: [".ru"],
    flagEmoji: "🇷🇺", drivingSide: "right",
    timezones: ["UTC+2 to UTC+12"],
    emergencyNumber: "112", internetUsers: "85%", gdpPerCapita: "$12,000",
  },
  CA: {
    code: "CA", name: "Canada", officialName: "Canada",
    capital: "Ottawa", region: "Americas", subregion: "Northern America", continent: "North America",
    population: 37000000, area: 9984670,
    currency: { code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
    languages: ["English", "French"], callingCode: "+1", tld: [".ca"],
    flagEmoji: "🇨🇦", drivingSide: "right",
    timezones: ["UTC-3:30 (NST)", "UTC-4 (AST)", "UTC-5 (EST)", "UTC-6 (CST)", "UTC-7 (MST)", "UTC-8 (PST)"],
    emergencyNumber: "911", internetUsers: "94%", gdpPerCapita: "$50,000",
  },
  AU: {
    code: "AU", name: "Australia", officialName: "Commonwealth of Australia",
    capital: "Canberra", region: "Oceania", subregion: "Australia and New Zealand", continent: "Oceania",
    population: 25700000, area: 7692024,
    currency: { code: "AUD", name: "Australian Dollar", symbol: "A$" },
    languages: ["English"], callingCode: "+61", tld: [".au"],
    flagEmoji: "🇦🇺", drivingSide: "left",
    timezones: ["UTC+8 (AWST)", "UTC+9:30 (ACST)", "UTC+10 (AEST)", "UTC+10:30 (ACDT)"],
    emergencyNumber: "000", internetUsers: "87%", gdpPerCapita: "$55,000",
  },
  MX: {
    code: "MX", name: "Mexico", officialName: "United Mexican States",
    capital: "Mexico City", region: "Americas", subregion: "Central America", continent: "North America",
    population: 128000000, area: 1964375,
    currency: { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
    languages: ["Spanish"], callingCode: "+52", tld: [".mx"],
    flagEmoji: "🇲🇽", drivingSide: "right",
    timezones: ["UTC-6 (CST)", "UTC-7 (MST)", "UTC-8 (PST)"],
    emergencyNumber: "911", internetUsers: "72%", gdpPerCapita: "$10,000",
  },
  KR: {
    code: "KR", name: "South Korea", officialName: "Republic of Korea",
    capital: "Seoul", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 51000000, area: 100210,
    currency: { code: "KRW", name: "South Korean Won", symbol: "₩" },
    languages: ["Korean"], callingCode: "+82", tld: [".kr"],
    flagEmoji: "🇰🇷", drivingSide: "right",
    timezones: ["UTC+9 (KST)"],
    emergencyNumber: "112", internetUsers: "97%", gdpPerCapita: "$33,000",
  },
  IT: {
    code: "IT", name: "Italy", officialName: "Italian Republic",
    capital: "Rome", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 59000000, area: 301340,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Italian"], callingCode: "+39", tld: [".it"],
    flagEmoji: "🇮🇹", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "75%", gdpPerCapita: "$34,000",
  },
  ES: {
    code: "ES", name: "Spain", officialName: "Kingdom of Spain",
    capital: "Madrid", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 46700000, area: 505990,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Spanish"], callingCode: "+34", tld: [".es"],
    flagEmoji: "🇪🇸", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "91%", gdpPerCapita: "$29,000",
  },
  NL: {
    code: "NL", name: "Netherlands", officialName: "Kingdom of the Netherlands",
    capital: "Amsterdam", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 17400000, area: 41543,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Dutch"], callingCode: "+31", tld: [".nl"],
    flagEmoji: "🇳🇱", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "95%", gdpPerCapita: "$57,000",
  },
  SA: {
    code: "SA", name: "Saudi Arabia", officialName: "Kingdom of Saudi Arabia",
    capital: "Riyadh", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 34800000, area: 2149690,
    currency: { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
    languages: ["Arabic"], callingCode: "+966", tld: [".sa"],
    flagEmoji: "🇸🇦", drivingSide: "right",
    timezones: ["UTC+3 (AST)"],
    emergencyNumber: "911", internetUsers: "95%", gdpPerCapita: "$24,000",
  },
  ZA: {
    code: "ZA", name: "South Africa", officialName: "Republic of South Africa",
    capital: "Pretoria", region: "Africa", subregion: "Southern Africa", continent: "Africa",
    population: 59000000, area: 1219090,
    currency: { code: "ZAR", name: "South African Rand", symbol: "R" },
    languages: ["Zulu", "Xhosa", "Afrikaans", "English"],
    callingCode: "+27", tld: [".za"],
    flagEmoji: "🇿🇦", drivingSide: "left",
    timezones: ["UTC+2 (SAST)"],
    emergencyNumber: "10111", internetUsers: "64%", gdpPerCapita: "$6,800",
  },
  NG: {
    code: "NG", name: "Nigeria", officialName: "Federal Republic of Nigeria",
    capital: "Abuja", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 206000000, area: 923768,
    currency: { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    languages: ["English", "Hausa", "Yoruba", "Igbo"],
    callingCode: "+234", tld: [".ng"],
    flagEmoji: "🇳🇬", drivingSide: "right",
    timezones: ["UTC+1 (WAT)"],
    emergencyNumber: "199", internetUsers: "51%", gdpPerCapita: "$2,200",
  },
  EG: {
    code: "EG", name: "Egypt", officialName: "Arab Republic of Egypt",
    capital: "Cairo", region: "Africa", subregion: "Northern Africa", continent: "Africa",
    population: 102000000, area: 1002450,
    currency: { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
    languages: ["Arabic"], callingCode: "+20", tld: [".eg"],
    flagEmoji: "🇪🇬", drivingSide: "right",
    timezones: ["UTC+2 (EET)"],
    emergencyNumber: "122", internetUsers: "72%", gdpPerCapita: "$4,200",
  },
  PK: {
    code: "PK", name: "Pakistan", officialName: "Islamic Republic of Pakistan",
    capital: "Islamabad", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 220000000, area: 881913,
    currency: { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    languages: ["Urdu", "English"], callingCode: "+92", tld: [".pk"],
    flagEmoji: "🇵🇰", drivingSide: "left",
    timezones: ["UTC+5 (PKT)"],
    emergencyNumber: "115", internetUsers: "47%", gdpPerCapita: "$1,600",
  },
  BD: {
    code: "BD", name: "Bangladesh", officialName: "People's Republic of Bangladesh",
    capital: "Dhaka", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 166000000, area: 147570,
    currency: { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    languages: ["Bengali"], callingCode: "+880", tld: [".bd"],
    flagEmoji: "🇧🇩", drivingSide: "left",
    timezones: ["UTC+6 (BST)"],
    emergencyNumber: "999", internetUsers: "39%", gdpPerCapita: "$2,200",
  },
  TR: {
    code: "TR", name: "Turkey", officialName: "Republic of Türkiye",
    capital: "Ankara", region: "Asia", subregion: "Western Asia", continent: "Asia/Europe",
    population: 84300000, area: 783562,
    currency: { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    languages: ["Turkish"], callingCode: "+90", tld: [".tr"],
    flagEmoji: "🇹🇷", drivingSide: "right",
    timezones: ["UTC+3 (TRT)"],
    emergencyNumber: "112", internetUsers: "79%", gdpPerCapita: "$9,600",
  },
  PH: {
    code: "PH", name: "Philippines", officialName: "Republic of the Philippines",
    capital: "Manila", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 110000000, area: 300000,
    currency: { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    languages: ["Filipino", "English"], callingCode: "+63", tld: [".ph"],
    flagEmoji: "🇵🇭", drivingSide: "right",
    timezones: ["UTC+8 (PST)"],
    emergencyNumber: "911", internetUsers: "73%", gdpPerCapita: "$3,500",
  },
  ID: {
    code: "ID", name: "Indonesia", officialName: "Republic of Indonesia",
    capital: "Jakarta", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 273500000, area: 1904569,
    currency: { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    languages: ["Indonesian"], callingCode: "+62", tld: [".id"],
    flagEmoji: "🇮🇩", drivingSide: "left",
    timezones: ["UTC+7 (WIB)", "UTC+8 (WITA)", "UTC+9 (WIT)"],
    emergencyNumber: "112", internetUsers: "62%", gdpPerCapita: "$4,000",
  },
  SE: {
    code: "SE", name: "Sweden", officialName: "Kingdom of Sweden",
    capital: "Stockholm", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 10400000, area: 450295,
    currency: { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    languages: ["Swedish"], callingCode: "+46", tld: [".se"],
    flagEmoji: "🇸🇪", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "95%", gdpPerCapita: "$55,000",
  },
  NO: {
    code: "NO", name: "Norway", officialName: "Kingdom of Norway",
    capital: "Oslo", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 5400000, area: 385207,
    currency: { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    languages: ["Norwegian"], callingCode: "+47", tld: [".no"],
    flagEmoji: "🇳🇴", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "97%", gdpPerCapita: "$82,000",
  },
  CH: {
    code: "CH", name: "Switzerland", officialName: "Swiss Confederation",
    capital: "Bern", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 8700000, area: 41285,
    currency: { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
    languages: ["German", "French", "Italian", "Romansh"], callingCode: "+41", tld: [".ch"],
    flagEmoji: "🇨🇭", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "93%", gdpPerCapita: "$86,000",
  },
  SG: {
    code: "SG", name: "Singapore", officialName: "Republic of Singapore",
    capital: "Singapore", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 5850000, area: 728,
    currency: { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
    languages: ["English", "Malay", "Mandarin", "Tamil"], callingCode: "+65", tld: [".sg"],
    flagEmoji: "🇸🇬", drivingSide: "left",
    timezones: ["UTC+8 (SGT)"],
    emergencyNumber: "999", internetUsers: "92%", gdpPerCapita: "$65,000",
  },
  AE: {
    code: "AE", name: "UAE", officialName: "United Arab Emirates",
    capital: "Abu Dhabi", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 9890000, area: 83600,
    currency: { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
    languages: ["Arabic"], callingCode: "+971", tld: [".ae"],
    flagEmoji: "🇦🇪", drivingSide: "right",
    timezones: ["UTC+4 (GST)"],
    emergencyNumber: "999", internetUsers: "99%", gdpPerCapita: "$43,000",
  },
  IL: {
    code: "IL", name: "Israel", officialName: "State of Israel",
    capital: "Jerusalem", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 9290000, area: 20770,
    currency: { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
    languages: ["Hebrew", "Arabic"], callingCode: "+972", tld: [".il"],
    flagEmoji: "🇮🇱", drivingSide: "right",
    timezones: ["UTC+2 (IST)", "UTC+3 (IDT)"],
    emergencyNumber: "100", internetUsers: "90%", gdpPerCapita: "$44,000",
  },
  NZ: {
    code: "NZ", name: "New Zealand", officialName: "New Zealand",
    capital: "Wellington", region: "Oceania", subregion: "Australia and New Zealand", continent: "Oceania",
    population: 5000000, area: 270467,
    currency: { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
    languages: ["English", "Māori"], callingCode: "+64", tld: [".nz"],
    flagEmoji: "🇳🇿", drivingSide: "left",
    timezones: ["UTC+12 (NZST)", "UTC+13 (NZDT)"],
    emergencyNumber: "111", internetUsers: "91%", gdpPerCapita: "$48,000",
  },
  AR: {
    code: "AR", name: "Argentina", officialName: "Argentine Republic",
    capital: "Buenos Aires", region: "Americas", subregion: "South America", continent: "South America",
    population: 45600000, area: 2780400,
    currency: { code: "ARS", name: "Argentine Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+54", tld: [".ar"],
    flagEmoji: "🇦🇷", drivingSide: "right",
    timezones: ["UTC-3 (ART)"],
    emergencyNumber: "911", internetUsers: "78%", gdpPerCapita: "$9,800",
  },
  PL: {
    code: "PL", name: "Poland", officialName: "Republic of Poland",
    capital: "Warsaw", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 38000000, area: 312679,
    currency: { code: "PLN", name: "Polish Złoty", symbol: "zł" },
    languages: ["Polish"], callingCode: "+48", tld: [".pl"],
    flagEmoji: "🇵🇱", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "86%", gdpPerCapita: "$17,000",
  },
  UA: {
    code: "UA", name: "Ukraine", officialName: "Ukraine",
    capital: "Kyiv", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 43500000, area: 603550,
    currency: { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    languages: ["Ukrainian"], callingCode: "+380", tld: [".ua"],
    flagEmoji: "🇺🇦", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "77%", gdpPerCapita: "$4,800",
  },
  TH: {
    code: "TH", name: "Thailand", officialName: "Kingdom of Thailand",
    capital: "Bangkok", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 70000000, area: 513120,
    currency: { code: "THB", name: "Thai Baht", symbol: "฿" },
    languages: ["Thai"], callingCode: "+66", tld: [".th"],
    flagEmoji: "🇹🇭", drivingSide: "left",
    timezones: ["UTC+7 (ICT)"],
    emergencyNumber: "191", internetUsers: "78%", gdpPerCapita: "$7,800",
  },
  VN: {
    code: "VN", name: "Vietnam", officialName: "Socialist Republic of Vietnam",
    capital: "Hanoi", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 97300000, area: 331212,
    currency: { code: "VND", name: "Vietnamese Đồng", symbol: "₫" },
    languages: ["Vietnamese"], callingCode: "+84", tld: [".vn"],
    flagEmoji: "🇻🇳", drivingSide: "right",
    timezones: ["UTC+7 (ICT)"],
    emergencyNumber: "113", internetUsers: "73%", gdpPerCapita: "$3,500",
  },
  MY: {
    code: "MY", name: "Malaysia", officialName: "Malaysia",
    capital: "Kuala Lumpur", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 32400000, area: 329847,
    currency: { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    languages: ["Malay", "English"], callingCode: "+60", tld: [".my"],
    flagEmoji: "🇲🇾", drivingSide: "left",
    timezones: ["UTC+8 (MYT)"],
    emergencyNumber: "999", internetUsers: "89%", gdpPerCapita: "$12,000",
  },
  IR: {
    code: "IR", name: "Iran", officialName: "Islamic Republic of Iran",
    capital: "Tehran", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 83500000, area: 1648195,
    currency: { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
    languages: ["Persian"], callingCode: "+98", tld: [".ir"],
    flagEmoji: "🇮🇷", drivingSide: "right",
    timezones: ["UTC+3:30 (IRST)", "UTC+4:30 (IRDT)"],
    emergencyNumber: "110", internetUsers: "72%", gdpPerCapita: "$6,000",
  },
  GH: {
    code: "GH", name: "Ghana", officialName: "Republic of Ghana",
    capital: "Accra", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 31000000, area: 238533,
    currency: { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
    languages: ["English"], callingCode: "+233", tld: [".gh"],
    flagEmoji: "🇬🇭", drivingSide: "right",
    timezones: ["UTC+0 (GMT)"],
    emergencyNumber: "999", internetUsers: "58%", gdpPerCapita: "$2,400",
  },
  KE: {
    code: "KE", name: "Kenya", officialName: "Republic of Kenya",
    capital: "Nairobi", region: "Africa", subregion: "Eastern Africa", continent: "Africa",
    population: 53800000, area: 580367,
    currency: { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
    languages: ["English", "Swahili"], callingCode: "+254", tld: [".ke"],
    flagEmoji: "🇰🇪", drivingSide: "left",
    timezones: ["UTC+3 (EAT)"],
    emergencyNumber: "999", internetUsers: "40%", gdpPerCapita: "$1,900",
  },
  PT: {
    code: "PT", name: "Portugal", officialName: "Portuguese Republic",
    capital: "Lisbon", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 10300000, area: 92212,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Portuguese"], callingCode: "+351", tld: [".pt"],
    flagEmoji: "🇵🇹", drivingSide: "right",
    timezones: ["UTC+0 (WET)", "UTC+1 (WEST)"],
    emergencyNumber: "112", internetUsers: "80%", gdpPerCapita: "$23,000",
  },
  GR: {
    code: "GR", name: "Greece", officialName: "Hellenic Republic",
    capital: "Athens", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 10700000, area: 131957,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Greek"], callingCode: "+30", tld: [".gr"],
    flagEmoji: "🇬🇷", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "81%", gdpPerCapita: "$19,000",
  },
  CL: {
    code: "CL", name: "Chile", officialName: "Republic of Chile",
    capital: "Santiago", region: "Americas", subregion: "South America", continent: "South America",
    population: 19100000, area: 756102,
    currency: { code: "CLP", name: "Chilean Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+56", tld: [".cl"],
    flagEmoji: "🇨🇱", drivingSide: "right",
    timezones: ["UTC-4 (CLT)", "UTC-3 (CLST)"],
    emergencyNumber: "133", internetUsers: "88%", gdpPerCapita: "$16,000",
  },

  // Europe
  AT: {
    code: "AT", name: "Austria", officialName: "Republic of Austria",
    capital: "Vienna", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 9042000, area: 83871,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["German"], callingCode: "+43", tld: [".at"],
    flagEmoji: "🇦🇹", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "88%", gdpPerCapita: "$52,000",
  },
  BE: {
    code: "BE", name: "Belgium", officialName: "Kingdom of Belgium",
    capital: "Brussels", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 11590000, area: 30528,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Dutch", "French", "German"], callingCode: "+32", tld: [".be"],
    flagEmoji: "🇧🇪", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "90%", gdpPerCapita: "$47,000",
  },
  DK: {
    code: "DK", name: "Denmark", officialName: "Kingdom of Denmark",
    capital: "Copenhagen", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 5831000, area: 42924,
    currency: { code: "DKK", name: "Danish Krone", symbol: "kr" },
    languages: ["Danish"], callingCode: "+45", tld: [".dk"],
    flagEmoji: "🇩🇰", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "97%", gdpPerCapita: "$62,000",
  },
  FI: {
    code: "FI", name: "Finland", officialName: "Republic of Finland",
    capital: "Helsinki", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 5531000, area: 338145,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Finnish", "Swedish"], callingCode: "+358", tld: [".fi"],
    flagEmoji: "🇫🇮", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "93%", gdpPerCapita: "$49,000",
  },
  CZ: {
    code: "CZ", name: "Czech Republic", officialName: "Czech Republic",
    capital: "Prague", region: "Europe", subregion: "Central Europe", continent: "Europe",
    population: 10700000, area: 78867,
    currency: { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    languages: ["Czech"], callingCode: "+420", tld: [".cz"],
    flagEmoji: "🇨🇿", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "83%", gdpPerCapita: "$26,000",
  },
  RO: {
    code: "RO", name: "Romania", officialName: "Romania",
    capital: "Bucharest", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 19290000, area: 238397,
    currency: { code: "RON", name: "Romanian Leu", symbol: "lei" },
    languages: ["Romanian"], callingCode: "+40", tld: [".ro"],
    flagEmoji: "🇷🇴", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "77%", gdpPerCapita: "$14,000",
  },
  HU: {
    code: "HU", name: "Hungary", officialName: "Hungary",
    capital: "Budapest", region: "Europe", subregion: "Central Europe", continent: "Europe",
    population: 9750000, area: 93028,
    currency: { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    languages: ["Hungarian"], callingCode: "+36", tld: [".hu"],
    flagEmoji: "🇭🇺", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "82%", gdpPerCapita: "$18,000",
  },
  IE: {
    code: "IE", name: "Ireland", officialName: "Republic of Ireland",
    capital: "Dublin", region: "Europe", subregion: "Northern Europe", continent: "Europe",
    population: 5006000, area: 70273,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Irish", "English"], callingCode: "+353", tld: [".ie"],
    flagEmoji: "🇮🇪", drivingSide: "left",
    timezones: ["UTC+0 (GMT)", "UTC+1 (IST)"],
    emergencyNumber: "112", internetUsers: "90%", gdpPerCapita: "$85,000",
  },
  SK: {
    code: "SK", name: "Slovakia", officialName: "Slovak Republic",
    capital: "Bratislava", region: "Europe", subregion: "Central Europe", continent: "Europe",
    population: 5460000, area: 49035,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Slovak"], callingCode: "+421", tld: [".sk"],
    flagEmoji: "🇸🇰", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "80%", gdpPerCapita: "$21,000",
  },
  HR: {
    code: "HR", name: "Croatia", officialName: "Republic of Croatia",
    capital: "Zagreb", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 4059000, area: 56594,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Croatian"], callingCode: "+385", tld: [".hr"],
    flagEmoji: "🇭🇷", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "83%", gdpPerCapita: "$17,000",
  },
  BG: {
    code: "BG", name: "Bulgaria", officialName: "Republic of Bulgaria",
    capital: "Sofia", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 6520000, area: 110879,
    currency: { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
    languages: ["Bulgarian"], callingCode: "+359", tld: [".bg"],
    flagEmoji: "🇧🇬", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "73%", gdpPerCapita: "$12,000",
  },
  RS: {
    code: "RS", name: "Serbia", officialName: "Republic of Serbia",
    capital: "Belgrade", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 6830000, area: 77474,
    currency: { code: "RSD", name: "Serbian Dinar", symbol: "din" },
    languages: ["Serbian"], callingCode: "+381", tld: [".rs"],
    flagEmoji: "🇷🇸", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "73%", gdpPerCapita: "$9,000",
  },
  LU: {
    code: "LU", name: "Luxembourg", officialName: "Grand Duchy of Luxembourg",
    capital: "Luxembourg City", region: "Europe", subregion: "Western Europe", continent: "Europe",
    population: 634000, area: 2586,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Luxembourgish", "French", "German"], callingCode: "+352", tld: [".lu"],
    flagEmoji: "🇱🇺", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "98%", gdpPerCapita: "$115,000",
  },
  SI: {
    code: "SI", name: "Slovenia", officialName: "Republic of Slovenia",
    capital: "Ljubljana", region: "Europe", subregion: "Southern Europe", continent: "Europe",
    population: 2100000, area: 20273,
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    languages: ["Slovenian"], callingCode: "+386", tld: [".si"],
    flagEmoji: "🇸🇮", drivingSide: "right",
    timezones: ["UTC+1 (CET)", "UTC+2 (CEST)"],
    emergencyNumber: "112", internetUsers: "79%", gdpPerCapita: "$27,000",
  },
  BY: {
    code: "BY", name: "Belarus", officialName: "Republic of Belarus",
    capital: "Minsk", region: "Europe", subregion: "Eastern Europe", continent: "Europe",
    population: 9450000, area: 207600,
    currency: { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
    languages: ["Belarusian", "Russian"], callingCode: "+375", tld: [".by"],
    flagEmoji: "🇧🇾", drivingSide: "right",
    timezones: ["UTC+3 (FET)"],
    emergencyNumber: "112", internetUsers: "79%", gdpPerCapita: "$7,000",
  },

  // Asia
  HK: {
    code: "HK", name: "Hong Kong", officialName: "Hong Kong Special Administrative Region",
    capital: "Hong Kong", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 7500000, area: 1104,
    currency: { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
    languages: ["Chinese", "English"], callingCode: "+852", tld: [".hk"],
    flagEmoji: "🇭🇰", drivingSide: "left",
    timezones: ["UTC+8 (HKT)"],
    emergencyNumber: "999", internetUsers: "92%", gdpPerCapita: "$49,000",
  },
  TW: {
    code: "TW", name: "Taiwan", officialName: "Republic of China (Taiwan)",
    capital: "Taipei", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 23570000, area: 36193,
    currency: { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    languages: ["Mandarin Chinese"], callingCode: "+886", tld: [".tw"],
    flagEmoji: "🇹🇼", drivingSide: "right",
    timezones: ["UTC+8 (CST)"],
    emergencyNumber: "110", internetUsers: "92%", gdpPerCapita: "$33,000",
  },
  KZ: {
    code: "KZ", name: "Kazakhstan", officialName: "Republic of Kazakhstan",
    capital: "Astana", region: "Asia", subregion: "Central Asia", continent: "Asia",
    population: 19000000, area: 2724900,
    currency: { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
    languages: ["Kazakh", "Russian"], callingCode: "+7", tld: [".kz"],
    flagEmoji: "🇰🇿", drivingSide: "right",
    timezones: ["UTC+5 (AQTT)", "UTC+6 (ALMT)"],
    emergencyNumber: "112", internetUsers: "82%", gdpPerCapita: "$9,000",
  },
  MM: {
    code: "MM", name: "Myanmar", officialName: "Republic of the Union of Myanmar",
    capital: "Naypyidaw", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 54410000, area: 676578,
    currency: { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
    languages: ["Burmese"], callingCode: "+95", tld: [".mm"],
    flagEmoji: "🇲🇲", drivingSide: "right",
    timezones: ["UTC+6:30 (MMT)"],
    emergencyNumber: "999", internetUsers: "39%", gdpPerCapita: "$1,400",
  },
  KH: {
    code: "KH", name: "Cambodia", officialName: "Kingdom of Cambodia",
    capital: "Phnom Penh", region: "Asia", subregion: "South-Eastern Asia", continent: "Asia",
    population: 16720000, area: 181035,
    currency: { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
    languages: ["Khmer"], callingCode: "+855", tld: [".kh"],
    flagEmoji: "🇰🇭", drivingSide: "right",
    timezones: ["UTC+7 (ICT)"],
    emergencyNumber: "117", internetUsers: "50%", gdpPerCapita: "$1,600",
  },
  NP: {
    code: "NP", name: "Nepal", officialName: "Federal Democratic Republic of Nepal",
    capital: "Kathmandu", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 29670000, area: 147181,
    currency: { code: "NPR", name: "Nepalese Rupee", symbol: "Rs" },
    languages: ["Nepali"], callingCode: "+977", tld: [".np"],
    flagEmoji: "🇳🇵", drivingSide: "left",
    timezones: ["UTC+5:45 (NPT)"],
    emergencyNumber: "100", internetUsers: "43%", gdpPerCapita: "$1,200",
  },
  LK: {
    code: "LK", name: "Sri Lanka", officialName: "Democratic Socialist Republic of Sri Lanka",
    capital: "Sri Jayawardenepura Kotte", region: "Asia", subregion: "Southern Asia", continent: "Asia",
    population: 21920000, area: 65610,
    currency: { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
    languages: ["Sinhala", "Tamil"], callingCode: "+94", tld: [".lk"],
    flagEmoji: "🇱🇰", drivingSide: "left",
    timezones: ["UTC+5:30 (SLST)"],
    emergencyNumber: "119", internetUsers: "34%", gdpPerCapita: "$4,000",
  },
  IQ: {
    code: "IQ", name: "Iraq", officialName: "Republic of Iraq",
    capital: "Baghdad", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 40220000, area: 438317,
    currency: { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
    languages: ["Arabic", "Kurdish"], callingCode: "+964", tld: [".iq"],
    flagEmoji: "🇮🇶", drivingSide: "right",
    timezones: ["UTC+3 (AST)"],
    emergencyNumber: "115", internetUsers: "49%", gdpPerCapita: "$5,000",
  },
  KW: {
    code: "KW", name: "Kuwait", officialName: "State of Kuwait",
    capital: "Kuwait City", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 4270000, area: 17818,
    currency: { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
    languages: ["Arabic"], callingCode: "+965", tld: [".kw"],
    flagEmoji: "🇰🇼", drivingSide: "right",
    timezones: ["UTC+3 (AST)"],
    emergencyNumber: "112", internetUsers: "99%", gdpPerCapita: "$29,000",
  },
  QA: {
    code: "QA", name: "Qatar", officialName: "State of Qatar",
    capital: "Doha", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 2880000, area: 11586,
    currency: { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
    languages: ["Arabic"], callingCode: "+974", tld: [".qa"],
    flagEmoji: "🇶🇦", drivingSide: "right",
    timezones: ["UTC+3 (AST)"],
    emergencyNumber: "999", internetUsers: "99%", gdpPerCapita: "$62,000",
  },
  OM: {
    code: "OM", name: "Oman", officialName: "Sultanate of Oman",
    capital: "Muscat", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 4520000, area: 309500,
    currency: { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
    languages: ["Arabic"], callingCode: "+968", tld: [".om"],
    flagEmoji: "🇴🇲", drivingSide: "right",
    timezones: ["UTC+4 (GST)"],
    emergencyNumber: "9999", internetUsers: "80%", gdpPerCapita: "$19,000",
  },
  LB: {
    code: "LB", name: "Lebanon", officialName: "Lebanese Republic",
    capital: "Beirut", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 6825000, area: 10452,
    currency: { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
    languages: ["Arabic"], callingCode: "+961", tld: [".lb"],
    flagEmoji: "🇱🇧", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "112", internetUsers: "78%", gdpPerCapita: "$4,000",
  },
  JO: {
    code: "JO", name: "Jordan", officialName: "Hashemite Kingdom of Jordan",
    capital: "Amman", region: "Asia", subregion: "Western Asia", continent: "Asia",
    population: 10200000, area: 89342,
    currency: { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
    languages: ["Arabic"], callingCode: "+962", tld: [".jo"],
    flagEmoji: "🇯🇴", drivingSide: "right",
    timezones: ["UTC+2 (EET)", "UTC+3 (EEST)"],
    emergencyNumber: "911", internetUsers: "71%", gdpPerCapita: "$4,300",
  },
  UZ: {
    code: "UZ", name: "Uzbekistan", officialName: "Republic of Uzbekistan",
    capital: "Tashkent", region: "Asia", subregion: "Central Asia", continent: "Asia",
    population: 34920000, area: 448978,
    currency: { code: "UZS", name: "Uzbekistani Som", symbol: "so'm" },
    languages: ["Uzbek"], callingCode: "+998", tld: [".uz"],
    flagEmoji: "🇺🇿", drivingSide: "right",
    timezones: ["UTC+5 (UZT)"],
    emergencyNumber: "103", internetUsers: "55%", gdpPerCapita: "$2,000",
  },
  MN: {
    code: "MN", name: "Mongolia", officialName: "Mongolia",
    capital: "Ulaanbaatar", region: "Asia", subregion: "Eastern Asia", continent: "Asia",
    population: 3330000, area: 1564116,
    currency: { code: "MNT", name: "Mongolian Tögrög", symbol: "₮" },
    languages: ["Mongolian"], callingCode: "+976", tld: [".mn"],
    flagEmoji: "🇲🇳", drivingSide: "right",
    timezones: ["UTC+7 (HOVT)", "UTC+8 (ULAT)"],
    emergencyNumber: "102", internetUsers: "62%", gdpPerCapita: "$4,200",
  },

  // Americas
  CO: {
    code: "CO", name: "Colombia", officialName: "Republic of Colombia",
    capital: "Bogotá", region: "Americas", subregion: "South America", continent: "South America",
    population: 51270000, area: 1141748,
    currency: { code: "COP", name: "Colombian Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+57", tld: [".co"],
    flagEmoji: "🇨🇴", drivingSide: "right",
    timezones: ["UTC-5 (COT)"],
    emergencyNumber: "123", internetUsers: "65%", gdpPerCapita: "$6,000",
  },
  PE: {
    code: "PE", name: "Peru", officialName: "Republic of Peru",
    capital: "Lima", region: "Americas", subregion: "South America", continent: "South America",
    population: 32970000, area: 1285216,
    currency: { code: "PEN", name: "Peruvian Sol", symbol: "S/." },
    languages: ["Spanish"], callingCode: "+51", tld: [".pe"],
    flagEmoji: "🇵🇪", drivingSide: "right",
    timezones: ["UTC-5 (PET)"],
    emergencyNumber: "105", internetUsers: "66%", gdpPerCapita: "$7,000",
  },
  VE: {
    code: "VE", name: "Venezuela", officialName: "Bolivarian Republic of Venezuela",
    capital: "Caracas", region: "Americas", subregion: "South America", continent: "South America",
    population: 28440000, area: 916445,
    currency: { code: "VES", name: "Venezuelan Bolívar Soberano", symbol: "Bs.S" },
    languages: ["Spanish"], callingCode: "+58", tld: [".ve"],
    flagEmoji: "🇻🇪", drivingSide: "right",
    timezones: ["UTC-4 (VET)"],
    emergencyNumber: "171", internetUsers: "72%", gdpPerCapita: "$1,700",
  },
  EC: {
    code: "EC", name: "Ecuador", officialName: "Republic of Ecuador",
    capital: "Quito", region: "Americas", subregion: "South America", continent: "South America",
    population: 17640000, area: 283561,
    currency: { code: "USD", name: "United States Dollar", symbol: "$" },
    languages: ["Spanish"], callingCode: "+593", tld: [".ec"],
    flagEmoji: "🇪🇨", drivingSide: "right",
    timezones: ["UTC-5 (ECT)", "UTC-6 (GALT)"],
    emergencyNumber: "911", internetUsers: "58%", gdpPerCapita: "$6,000",
  },
  BO: {
    code: "BO", name: "Bolivia", officialName: "Plurinational State of Bolivia",
    capital: "Sucre", region: "Americas", subregion: "South America", continent: "South America",
    population: 11670000, area: 1098581,
    currency: { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
    languages: ["Spanish", "Quechua", "Aymara"], callingCode: "+591", tld: [".bo"],
    flagEmoji: "🇧🇴", drivingSide: "right",
    timezones: ["UTC-4 (BOT)"],
    emergencyNumber: "110", internetUsers: "44%", gdpPerCapita: "$3,500",
  },
  UY: {
    code: "UY", name: "Uruguay", officialName: "Oriental Republic of Uruguay",
    capital: "Montevideo", region: "Americas", subregion: "South America", continent: "South America",
    population: 3474000, area: 176215,
    currency: { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
    languages: ["Spanish"], callingCode: "+598", tld: [".uy"],
    flagEmoji: "🇺🇾", drivingSide: "right",
    timezones: ["UTC-3 (UYT)"],
    emergencyNumber: "911", internetUsers: "88%", gdpPerCapita: "$17,000",
  },
  CR: {
    code: "CR", name: "Costa Rica", officialName: "Republic of Costa Rica",
    capital: "San José", region: "Americas", subregion: "Central America", continent: "North America",
    population: 5094000, area: 51100,
    currency: { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
    languages: ["Spanish"], callingCode: "+506", tld: [".cr"],
    flagEmoji: "🇨🇷", drivingSide: "right",
    timezones: ["UTC-6 (CST)"],
    emergencyNumber: "911", internetUsers: "74%", gdpPerCapita: "$12,000",
  },
  GT: {
    code: "GT", name: "Guatemala", officialName: "Republic of Guatemala",
    capital: "Guatemala City", region: "Americas", subregion: "Central America", continent: "North America",
    population: 17110000, area: 108889,
    currency: { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
    languages: ["Spanish"], callingCode: "+502", tld: [".gt"],
    flagEmoji: "🇬🇹", drivingSide: "right",
    timezones: ["UTC-6 (CST)"],
    emergencyNumber: "110", internetUsers: "47%", gdpPerCapita: "$4,600",
  },
  PA: {
    code: "PA", name: "Panama", officialName: "Republic of Panama",
    capital: "Panama City", region: "Americas", subregion: "Central America", continent: "North America",
    population: 4351000, area: 75417,
    currency: { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
    languages: ["Spanish"], callingCode: "+507", tld: [".pa"],
    flagEmoji: "🇵🇦", drivingSide: "right",
    timezones: ["UTC-5 (EST)"],
    emergencyNumber: "911", internetUsers: "65%", gdpPerCapita: "$15,000",
  },
  DO: {
    code: "DO", name: "Dominican Republic", officialName: "Dominican Republic",
    capital: "Santo Domingo", region: "Americas", subregion: "Caribbean", continent: "North America",
    population: 10850000, area: 48671,
    currency: { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
    languages: ["Spanish"], callingCode: "+1", tld: [".do"],
    flagEmoji: "🇩🇴", drivingSide: "right",
    timezones: ["UTC-4 (AST)"],
    emergencyNumber: "911", internetUsers: "74%", gdpPerCapita: "$9,000",
  },
  CU: {
    code: "CU", name: "Cuba", officialName: "Republic of Cuba",
    capital: "Havana", region: "Americas", subregion: "Caribbean", continent: "North America",
    population: 11330000, area: 109884,
    currency: { code: "CUP", name: "Cuban Peso", symbol: "$" },
    languages: ["Spanish"], callingCode: "+53", tld: [".cu"],
    flagEmoji: "🇨🇺", drivingSide: "right",
    timezones: ["UTC-5 (CST)", "UTC-4 (CDT)"],
    emergencyNumber: "106", internetUsers: "68%", gdpPerCapita: "$8,000",
  },
  TT: {
    code: "TT", name: "Trinidad and Tobago", officialName: "Republic of Trinidad and Tobago",
    capital: "Port of Spain", region: "Americas", subregion: "Caribbean", continent: "North America",
    population: 1399000, area: 5130,
    currency: { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$" },
    languages: ["English"], callingCode: "+1", tld: [".tt"],
    flagEmoji: "🇹🇹", drivingSide: "left",
    timezones: ["UTC-4 (AST)"],
    emergencyNumber: "999", internetUsers: "77%", gdpPerCapita: "$17,000",
  },
  JM: {
    code: "JM", name: "Jamaica", officialName: "Jamaica",
    capital: "Kingston", region: "Americas", subregion: "Caribbean", continent: "North America",
    population: 2961000, area: 10991,
    currency: { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
    languages: ["English"], callingCode: "+1", tld: [".jm"],
    flagEmoji: "🇯🇲", drivingSide: "left",
    timezones: ["UTC-5 (EST)"],
    emergencyNumber: "119", internetUsers: "55%", gdpPerCapita: "$5,500",
  },
  HN: {
    code: "HN", name: "Honduras", officialName: "Republic of Honduras",
    capital: "Tegucigalpa", region: "Americas", subregion: "Central America", continent: "North America",
    population: 10280000, area: 112492,
    currency: { code: "HNL", name: "Honduran Lempira", symbol: "L" },
    languages: ["Spanish"], callingCode: "+504", tld: [".hn"],
    flagEmoji: "🇭🇳", drivingSide: "right",
    timezones: ["UTC-6 (CST)"],
    emergencyNumber: "911", internetUsers: "32%", gdpPerCapita: "$2,500",
  },
  SV: {
    code: "SV", name: "El Salvador", officialName: "Republic of El Salvador",
    capital: "San Salvador", region: "Americas", subregion: "Central America", continent: "North America",
    population: 6490000, area: 21041,
    currency: { code: "USD", name: "United States Dollar", symbol: "$" },
    languages: ["Spanish"], callingCode: "+503", tld: [".sv"],
    flagEmoji: "🇸🇻", drivingSide: "right",
    timezones: ["UTC-6 (CST)"],
    emergencyNumber: "911", internetUsers: "33%", gdpPerCapita: "$4,000",
  },

  // Africa
  ET: {
    code: "ET", name: "Ethiopia", officialName: "Federal Democratic Republic of Ethiopia",
    capital: "Addis Ababa", region: "Africa", subregion: "Eastern Africa", continent: "Africa",
    population: 117900000, area: 1104300,
    currency: { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    languages: ["Amharic"], callingCode: "+251", tld: [".et"],
    flagEmoji: "🇪🇹", drivingSide: "right",
    timezones: ["UTC+3 (EAT)"],
    emergencyNumber: "991", internetUsers: "15%", gdpPerCapita: "$1,000",
  },
  TZ: {
    code: "TZ", name: "Tanzania", officialName: "United Republic of Tanzania",
    capital: "Dodoma", region: "Africa", subregion: "Eastern Africa", continent: "Africa",
    population: 61500000, area: 945087,
    currency: { code: "TZS", name: "Tanzanian Shilling", symbol: "Sh" },
    languages: ["Swahili", "English"], callingCode: "+255", tld: [".tz"],
    flagEmoji: "🇹🇿", drivingSide: "left",
    timezones: ["UTC+3 (EAT)"],
    emergencyNumber: "112", internetUsers: "25%", gdpPerCapita: "$1,100",
  },
  DZ: {
    code: "DZ", name: "Algeria", officialName: "People's Democratic Republic of Algeria",
    capital: "Algiers", region: "Africa", subregion: "Northern Africa", continent: "Africa",
    population: 44700000, area: 2381741,
    currency: { code: "DZD", name: "Algerian Dinar", symbol: "دج" },
    languages: ["Arabic", "Berber"], callingCode: "+213", tld: [".dz"],
    flagEmoji: "🇩🇿", drivingSide: "right",
    timezones: ["UTC+1 (CET)"],
    emergencyNumber: "17", internetUsers: "64%", gdpPerCapita: "$4,000",
  },
  MA: {
    code: "MA", name: "Morocco", officialName: "Kingdom of Morocco",
    capital: "Rabat", region: "Africa", subregion: "Northern Africa", continent: "Africa",
    population: 37340000, area: 446550,
    currency: { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
    languages: ["Arabic", "Berber"], callingCode: "+212", tld: [".ma"],
    flagEmoji: "🇲🇦", drivingSide: "right",
    timezones: ["UTC+1 (WET)"],
    emergencyNumber: "190", internetUsers: "74%", gdpPerCapita: "$3,400",
  },
  TN: {
    code: "TN", name: "Tunisia", officialName: "Republic of Tunisia",
    capital: "Tunis", region: "Africa", subregion: "Northern Africa", continent: "Africa",
    population: 11820000, area: 163610,
    currency: { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
    languages: ["Arabic"], callingCode: "+216", tld: [".tn"],
    flagEmoji: "🇹🇳", drivingSide: "right",
    timezones: ["UTC+1 (CET)"],
    emergencyNumber: "197", internetUsers: "67%", gdpPerCapita: "$3,800",
  },
  AO: {
    code: "AO", name: "Angola", officialName: "Republic of Angola",
    capital: "Luanda", region: "Africa", subregion: "Middle Africa", continent: "Africa",
    population: 32870000, area: 1246700,
    currency: { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
    languages: ["Portuguese"], callingCode: "+244", tld: [".ao"],
    flagEmoji: "🇦🇴", drivingSide: "right",
    timezones: ["UTC+1 (WAT)"],
    emergencyNumber: "113", internetUsers: "22%", gdpPerCapita: "$2,000",
  },
  UG: {
    code: "UG", name: "Uganda", officialName: "Republic of Uganda",
    capital: "Kampala", region: "Africa", subregion: "Eastern Africa", continent: "Africa",
    population: 47120000, area: 241038,
    currency: { code: "UGX", name: "Ugandan Shilling", symbol: "Sh" },
    languages: ["English", "Swahili"], callingCode: "+256", tld: [".ug"],
    flagEmoji: "🇺🇬", drivingSide: "left",
    timezones: ["UTC+3 (EAT)"],
    emergencyNumber: "999", internetUsers: "26%", gdpPerCapita: "$900",
  },
  CI: {
    code: "CI", name: "Côte d'Ivoire", officialName: "Republic of Côte d'Ivoire",
    capital: "Yamoussoukro", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 26380000, area: 322463,
    currency: { code: "XOF", name: "West African CFA Franc", symbol: "Fr" },
    languages: ["French"], callingCode: "+225", tld: [".ci"],
    flagEmoji: "🇨🇮", drivingSide: "right",
    timezones: ["UTC+0 (GMT)"],
    emergencyNumber: "110", internetUsers: "46%", gdpPerCapita: "$2,300",
  },
  SN: {
    code: "SN", name: "Senegal", officialName: "Republic of Senegal",
    capital: "Dakar", region: "Africa", subregion: "Western Africa", continent: "Africa",
    population: 17200000, area: 196722,
    currency: { code: "XOF", name: "West African CFA Franc", symbol: "Fr" },
    languages: ["French"], callingCode: "+221", tld: [".sn"],
    flagEmoji: "🇸🇳", drivingSide: "right",
    timezones: ["UTC+0 (GMT)"],
    emergencyNumber: "17", internetUsers: "46%", gdpPerCapita: "$1,600",
  },
  CM: {
    code: "CM", name: "Cameroon", officialName: "Republic of Cameroon",
    capital: "Yaoundé", region: "Africa", subregion: "Middle Africa", continent: "Africa",
    population: 26550000, area: 475442,
    currency: { code: "XAF", name: "Central African CFA Franc", symbol: "Fr" },
    languages: ["French", "English"], callingCode: "+237", tld: [".cm"],
    flagEmoji: "🇨🇲", drivingSide: "right",
    timezones: ["UTC+1 (WAT)"],
    emergencyNumber: "117", internetUsers: "35%", gdpPerCapita: "$1,500",
  },
};

export function getCountryIntel(code: string): CountryIntel | null {
  return COUNTRY_DATA[code.toUpperCase()] ?? null;
}

// Pre-built reverse lookup: calling code → first matching ISO country code (O(1) per call)
const CALLING_CODE_MAP = new Map<string, string>(
  Object.entries(COUNTRY_DATA).map(([cc, data]) => [data.callingCode, cc])
);

export function getCallingCodeToCountry(callingCode: string): string | null {
  const key = callingCode.startsWith("+") ? callingCode : `+${callingCode}`;
  return CALLING_CODE_MAP.get(key) ?? null;
}

export { COUNTRY_DATA };
