// Known disposable / throwaway email domains.
// Sources: public domain lists, manually curated.
export const DISPOSABLE_DOMAINS = new Set<string>([
  // ── Major temp-mail services ────────────────────────────────────────────────
  "mailinator.com","mailinator2.com","mailinator.net",
  "guerrillamail.com","guerrillamail.org","guerrillamail.net",
  "guerrillamail.info","guerrillamail.de","guerrillamail.biz",
  "guerrillamailblock.com","grr.la","sharklasers.com","spam4.me",
  "yopmail.com","yopmail.fr","cool.fr.nf","jetable.fr.nf",
  "nospam.ze.tc","nomail.xl.cx","mega.zik.dj","speed.1s.fr",
  "courriel.fr.nf","moncourrier.fr.nf","monemail.fr.nf","monmail.fr.nf",
  "tempmail.com","temp-mail.org","temp-mail.io","tempmail.net",
  "tempmail.org","tempinbox.com","tempinbox.net","throwaway.email",
  "throwam.com","trashmail.com","trashmail.at","trashmail.io",
  "trashmail.me","trashmail.net","trashmail.org","trashdevil.com",
  "trashdevil.de","trashmail.de",
  "fakeinbox.com","fakeinbox.net","fakemail.net","fakermail.com",
  "mailnull.com","mailnesia.com","mailscrap.com","mailbolt.com",
  "mailexpire.com","mailzilla.com","mailzilla.org",
  "spamgourmet.com","spamgourmet.net","spamgourmet.org",
  "spamherr.com","spam.la","spamfree24.org","spamspot.com",
  "spamthis.co.uk","spamthisplease.com",
  "dispostable.com","discard.email","discardmail.com","discardmail.de",
  "pookmail.com","mytrashmail.com","maileater.com",
  "mail-temporaire.fr","jetable.com","jetable.net","jetable.org",
  "jetable.pro","jnxjn.com","jourrapide.com",
  "dodgit.com","dodgit.org","bugmenot.com",
  "getonemail.com","getonemail.net","spammotel.com",
  "filzmail.com","binkmail.com","bobmail.info","chammy.info",
  "devnullmail.com","letthemeatspam.com","mattmoney.us",
  "mt2009.com","mt2014.com","mycleaninbox.net","myfastmail.com",
  "nospamfor.us","nospammail.net","nowmymail.com","objectmail.com",
  "obobbo.com","oneoffemail.com","pjjkp.com","politikerclub.de",
  "privy-mail.com","privy-mail.de","proxymail.eu","rklips.com",
  "rppkn.com","rtrtr.com","s0ny.net","safe-mail.net",
  "safetymail.info","safetypost.de","sandelf.de","saynotospams.com",
  "self-destruct.email","sendspamhere.com","sharklasers.com",
  "sharedmailbox.org","shieldemail.com","shiftmail.com",
  "shitmail.me","shitmail.org","shortmail.net","sibmail.com",
  "sinnlos-mail.de","smashmail.de","smellfear.com","snakemail.com",
  "sneakemail.com","sofort-mail.de","sogetthis.com","soodonims.com",
  "spam.su","spambob.com","spambob.net","spambob.org",
  "spambooger.com","spamcero.com","spamcon.org",
  "spamcorptastic.com","spamcowboy.com","spamcowboy.net",
  "spamcowboy.org","spamday.com","spamdecoy.net",
  "spamex.com","spamfree.eu","spamgoes.in","spamherelots.com",
  "spamherelots.net","spamhole.com","spamify.com","spaminator.de",
  "spamkill.info","spaml.com","spaml.de","spammotel.com",
  "spamoff.de","spamrelayer.com","spamslicer.com","spamstack.net",
  "spamthis.co.uk","spamtroll.net","spamwc.de","speedymail.org",
  "spr.io","squizzy.de","ssoia.com","stinkefinger.net",
  "stuffmail.de","super-auswahl.de","supergreatmail.com",
  "supermailer.jp","suremail.info","svk.jp",
  "tempemail.com","tempemail.net","tempemail.org",
  "tempinbox.co.uk","temporaryemail.net","temporaryemail.us",
  "temporaryforwarding.com","temporaryinbox.com","temporarymail.org",
  "tempr.email","tempsky.com","thankyou2010.com",
  "thecloudindex.com","thelimestones.com","thisisnotmyrealemail.com",
  "throwam.com","throwamail.com","thunderbol.com","tilien.com",
  "tittbit.in","tmail.com","tmail.io","tmailinator.com",
  "toiea.com","toomail.biz","topranklist.de","tradermail.info",
  "trash-mail.at","trash-mail.com","trash-mail.de","trash-mail.ga",
  "trash-mail.io","trash-mail.me","trash-mail.tk","trash2009.com",
  "trashcanmail.com","trashemail.de","trashimail.com",
  "trashmailer.com","trbvm.com","trud.us","turual.com",
  "twinmail.de","tyldd.com","uggsrock.com","umail.net",
  "undo.it","unids.com","uorak.com","uroid.com","us.af",
  "valemail.net","vctel.com","venompen.com","viditag.com",
  "viewcastmedia.com","viewcastmedia.net","viewcastmedia.org",
  "viralplays.com","vpn.st","vsimcard.com","vubby.com",
  "walala.org","walkmail.net","walkmail.ru","wetrainbayarea.com",
  "wetrainbayarea.org","wh4f.org","whatiaas.com","whatifnot.com",
  "whyspam.me","wickmail.net","wilemail.com","willhackforfood.biz",
  "willselfdestruct.com","wimsg.com","winemaven.info","wronghead.com",
  "www.e4ward.com","wwwnew.eu","x1post.com","xagloo.com",
  "xemaps.com","xents.com","xmaily.com","xoxy.net",
  "xsmail.com","xyzfree.net","yapped.net","yeah.net",
  "yep.it","yogamaven.com","yopmail.net","youmailr.com",
  "ypmail.webarnak.fr.eu.org","yuurok.com","z1p.biz",
  "za.com","zehnminuten.de","zehnminutenmail.de",
  "zippymail.info","zoemail.com","zoemail.net","zoemail.org",
  "zomg.info",
  // ── Additional burner services ───────────────────────────────────────────────
  "10minutemail.com","10minutemail.net","10minutemail.org","10minutemail.de",
  "10minutemail.co.uk","10minutemail.info","10minutemail.io",
  "10minutemail.me","10minutemail.nl","10minutemail.pro",
  "10minutemail.us","10minutemail.be","10minutemail.cf",
  "10minutemail.co.za","10minutemail.es","10minutemail.eu",
  "20minutemail.com","20minutemail.it",
  "60minutemail.com","1minutemail.com",
  "5minutemail.com","5minutemail.net",
  "mintemail.com","minutemail.com","minutemailbox.com",
  "mymail-in.net","mymailoasis.com","myphantomemail.com",
  "dispostable.com","dispostable.net","disposablemail.com",
  "disposablemail.net","disposablemail.org","disposableinbox.com",
  "disposeamail.com","disposemail.com",
  "crazymailing.com","cutout.club","clrmail.com","cock.li",
  "deadaddress.com","deadletter.ga","dingbone.com",
  "dingfone.com","discard.email","discardmail.com",
  "dontreg.com","dontsendmespam.de","drdrb.com","drdrb.net",
  "dropcake.de","dudmail.com","dump-email.info","dumpandfuck.com",
  "dumpyemail.com","duskmail.com",
  "e4ward.com","easytrashmail.com","edgex.ru","email-fake.com",
  "email-temp.com","email60.com","emailage.cf","emaildienst.de",
  "emailgo.de","emailias.com","emailinfive.com","emailisvalid.com",
  "emailmiser.com","emailna.com","emailnax.com","emailo.pro",
  "emailproxsy.com","emailresort.com","emailsensei.com",
  "emailspam.cf","emailspam.ga","emailspam.gq","emailspam.ml",
  "emailspam.tk","emailthe.net","emailtmp.com","emailwarden.com",
  "emailx.at.hm","emailxfer.com","emailz.cf","emailz.ga",
  "emailz.gq","emailz.ml","emeil.in","emeil.ir",
  "emeraldwebmail.com","emltmp.com",
  "rtrtr.com","s0ny.net","safetymail.info",
  "inboxbear.com","inbox.si","incognitomail.com",
  "incognitomail.net","incognitomail.org",
  "instant-mail.de","instantemailaddress.com","instanttrash.email",
  "irabops.com","ircbox.xyz","irish2me.com","iroid.com",
  "is.af","iubridge.com","iwi.net",
  "jetable.com","jnxjn.com","jobbikmarko.hu",
  "junk.to","junklot.com","junkmail.com","junkmail.ga",
  "junkmail.gq","jupimail.com",
  "kasmail.com","kaspop.com","keepmymail.com","killmail.com",
  "killmail.net","kimsdisk.com","klzlk.com","koszmail.pl",
  "kurzepost.de","kusrc.com",
  "l33r.eu","lackmail.ru","lhsdv.com","liamcyrus.com",
  "lol.ovpn.to","lolfreak.net","lookugly.com","lortemail.dk",
  "losemymail.com","lroid.com","lukop.dk",
  "m21.cc","maboard.com","mail-filter.com","mail-j.com",
  "mail-me.com","mail-temp.com","mail.by","mail.mezimages.net",
  "mail1a.de","mail2rss.org","mail333.com","mailbidon.com",
  "mailblocks.com","mailbucket.org","mailcat.biz","mailcatch.com",
  "maildrop.cc","maileme101.com","mailforspam.com","mailfreeonline.com",
  "mailfs.com","mailguard.me","mailimate.com","mailimails.com",
  "mailincubator.com","mailinatör.com","mailkeptprivate.com",
  "mailmate.com","mailme.ir","mailme.lv","mailme24.com",
  "mailmetrash.com","mailmoat.com","mailna.co","mailna.me",
  "mailnew.com","mailnobody.com","mailnull.com","mailnzia.com",
  "mailpick.biz","mailproxsy.com","mailquack.com","mailredirect.org",
  "mailrock.biz","mailscrap.com","mailseal.de","mailshell.com",
  "mailsiphon.com","mailslite.com","mailsource.info","mailspot.org",
  "mailsuite.com","mailtemp.info","mailtemporal.com","mailtemporary.com",
  "mailtome.de","mailtothis.com","mailtrash.net","mailtv.net",
  "mailtv.tv","mailway.com","mailwithyou.com","manie.de",
  "manybrain.com","mbx.cc","mcache.net","mega.zik.dj",
  "meinspamschutz.de","meltmail.com","messagebeamer.de",
  "mezimages.net","mfsa.ru","mierdamail.com","migumail.com",
  "milesemail.com","milkwoodradio.org","minex-coin.com",
  "ministerial.com","mintemail.com","misterpinball.de",
  "mjukglass.nu","mmail.igg.biz","moakt.cc","moakt.co",
  "moakt.com","moakt.ws","mobail.im","mockmyid.com",
  "moncourrier.fr.nf","monemail.fr.nf","monmail.fr.nf",
  "mopjsus.com","morriesworld.ml","motique.de","mountainregionallibrary.net",
  "mozartmail.com","msa.minsmail.com",
  "mt2009.com","mt2014.com","mt2015.com","mt2016.com",
  "mycleaninbox.net","myfakeinbox.com","myfakemail.ga",
  "myfakemail.tk","myfastmail.com","mymailoasis.com",
]);

/** Free / personal webmail providers (not disposable — real accounts) */
export const FREE_WEBMAIL_DOMAINS = new Set<string>([
  // Google
  "gmail.com","googlemail.com","google.com",
  // Microsoft
  "hotmail.com","hotmail.co.uk","hotmail.fr","hotmail.de",
  "hotmail.it","hotmail.es","hotmail.nl","hotmail.se",
  "outlook.com","outlook.co.uk","outlook.fr","outlook.de",
  "outlook.it","outlook.es","outlook.com.au","outlook.co.nz",
  "outlook.jp","outlook.sa","outlook.ae","outlook.sg",
  "live.com","live.co.uk","live.fr","live.de","live.it",
  "live.nl","live.se","live.dk","live.be","live.no",
  "live.ca","live.com.au","live.ie","live.jp","live.ru",
  "msn.com","windowslive.com",
  // Apple
  "icloud.com","me.com","mac.com",
  // Yahoo
  "yahoo.com","yahoo.co.uk","yahoo.fr","yahoo.de","yahoo.it",
  "yahoo.es","yahoo.co.jp","yahoo.com.au","yahoo.co.in",
  "yahoo.com.br","yahoo.ca","yahoo.co.nz","yahoo.com.ar",
  "yahoo.com.mx","yahoo.com.sg","yahoo.com.ph","yahoo.gr",
  "ymail.com","rocketmail.com",
  // AOL
  "aol.com","aim.com","aol.co.uk","aol.de","aol.fr",
  // Mail.com group
  "mail.com","email.com","gmx.com","gmx.de","gmx.net",
  "gmx.us","gmx.at","gmx.ch","gmx.co.uk","gmx.es",
  "gmx.fr","gmx.it","gmx.info","gmx.mobi","gmx.org",
  "web.de",
  // Russian
  "yandex.com","yandex.ru","yandex.ua","yandex.kz","yandex.by",
  "ya.ru","mail.ru","inbox.ru","list.ru","bk.ru",
  "rambler.ru","ro.ru","lenta.ru","autorambler.ru","myrambler.ru",
  // Chinese
  "qq.com","163.com","126.com","sina.com","sina.cn",
  "sohu.com","foxmail.com","yeah.net",
  // Other global
  "t-online.de","freenet.de","web.de",
  "orange.fr","free.fr","sfr.fr","laposte.net",
  "libero.it","virgilio.it","alice.it","tim.it",
  "rediffmail.com","indiatimes.com","sify.com",
  "naver.com","daum.net","hanmail.net","nate.com",
  "ukr.net","i.ua","bigmir.net","email.ua",
  "seznam.cz","post.cz","email.cz","centrum.cz","atlas.cz",
  "wp.pl","o2.pl","interia.pl","onet.pl","gazeta.pl",
  "inbox.com","hushmail.com","hush.com","hush.ai",
  "zoho.com","zohomail.com","zohomail.eu","zohomail.in",
  "fastmail.com","fastmail.fm","fastmail.to","fastmail.net",
  "fastmail.org","fastmail.cn","fastmail.es","fastmail.de",
  "fastmail.in","fastmail.jp","fastmail.se","fastmail.to",
  "lycos.com","lycos.co.uk","lycos.de","lycos.fr",
  "netscape.net","excite.com","iname.com","juno.com",
]);

/** Privacy-focused email providers */
export const PRIVACY_DOMAINS = new Set<string>([
  "protonmail.com","protonmail.ch","protonmail.net",
  "pm.me","proton.me",
  "tutanota.com","tuta.io","tutanota.de","keemail.me","tuta.com",
  "mailfence.com",
  "startmail.com",
  "runbox.com",
  "posteo.de","posteo.net","posteo.org","posteo.eu",
  "disroot.org",
  "riseup.net",
  "ctemplar.com",
  "skiff.com",
  "cock.li","airmail.cc","loves.dakimakura.eu",
  "onionmail.org","tormail.org",
  "countermail.com",
  "lavabit.com",
  "hushmail.com","hush.com","hush.ai",
  "guerrillamail.com", // listed here as some use it for real privacy
  "anonaddy.com","anonaddy.me",
  "simplelogin.io","simplelogin.co","simplelogin.fr",
]);

/** Role-based address prefixes — generic, not personal */
export const ROLE_PREFIXES = new Set<string>([
  "admin","administrator","abuse","billing","contact",
  "help","hostmaster","info","jobs","mailer-daemon",
  "marketing","noc","noreply","no-reply","postmaster",
  "privacy","sales","security","service","spam",
  "support","sysadmin","tech","technical","webmaster",
  "press","media","pr","partnerships","legal","hr",
  "careers","hello","team","office","mail","root",
  "accounts","finance","newsletter","notify","notifications",
  "orders","payments","reports","alerts","bot","api",
]);
