// ── Case report export / import (chain-of-custody) ───────────────────────────
// Produces an analyst-grade, self-describing export of an investigation case in
// two formats:
//   • JSON  — machine-readable, re-importable, with a SHA-256 integrity hash
//             over the case payload so tampering is detectable.
//   • Markdown — human-readable report (entities table, notes, provenance).
// Pure functions + Web Crypto; runs entirely client-side.

import type { InvestigationCase, CaseEntity } from "../types";

export const REPORT_SCHEMA = "heaven-geointel/case-report@1";
const APP_VERSION = "1.3.0";

export interface CaseReportEnvelope {
  tool: "HEAVEN-GeoIntel";
  schema: typeof REPORT_SCHEMA;
  version: string;
  exportedAt: string;          // ISO-8601
  integrity: { algo: "SHA-256"; hash: string };
  case: CasePayload;
}

interface CasePayload {
  name: string;
  createdAt: number;
  updatedAt: number;
  entities: CaseEntity[];
  notes: string;
}

// Stable, key-ordered payload so the hash is deterministic across exports.
function payloadOf(c: InvestigationCase): CasePayload {
  return {
    name: c.name,
    createdAt: c.createdAt,
    updatedAt: c.updatedAt,
    entities: c.entities
      .map((e) => ({ kind: e.kind, value: e.value, addedAt: e.addedAt, note: e.note }))
      .sort((a, b) => a.kind.localeCompare(b.kind) || a.value.localeCompare(b.value)),
    notes: c.notes ?? "",
  };
}

function canonical(p: CasePayload): string {
  // JSON.stringify with the object built in a fixed key order = canonical form.
  return JSON.stringify(p);
}

export async function sha256Hex(input: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

export async function buildCaseJson(c: InvestigationCase): Promise<{ json: string; hash: string }> {
  const payload = payloadOf(c);
  const hash = await sha256Hex(canonical(payload));
  const envelope: CaseReportEnvelope = {
    tool: "HEAVEN-GeoIntel",
    schema: REPORT_SCHEMA,
    version: APP_VERSION,
    exportedAt: new Date().toISOString(),
    integrity: { algo: "SHA-256", hash },
    case: payload,
  };
  return { json: JSON.stringify(envelope, null, 2), hash };
}

export async function buildCaseMarkdown(c: InvestigationCase): Promise<string> {
  const payload = payloadOf(c);
  const hash = await sha256Hex(canonical(payload));
  const fmt = (ms: number) => new Date(ms).toISOString();
  const rows = payload.entities.length
    ? payload.entities.map((e) => `| ${e.kind} | \`${e.value.replace(/\|/g, "\\|")}\` | ${fmt(e.addedAt)} | ${(e.note ?? "").replace(/\|/g, "\\|")} |`).join("\n")
    : "| — | _no identifiers_ | — | — |";

  return [
    `# HEAVEN-GeoIntel — Investigation Report`,
    ``,
    `**Case:** ${payload.name}`,
    `**Created:** ${fmt(payload.createdAt)}`,
    `**Last updated:** ${fmt(payload.updatedAt)}`,
    `**Exported:** ${new Date().toISOString()}`,
    `**Identifiers:** ${payload.entities.length}`,
    ``,
    `## Identifiers`,
    ``,
    `| Type | Value | Added | Note |`,
    `|------|-------|-------|------|`,
    rows,
    ``,
    `## Analyst notes`,
    ``,
    payload.notes.trim() ? payload.notes.trim() : "_None._",
    ``,
    `---`,
    ``,
    `Integrity (SHA-256 of case payload): \`${hash}\``,
    ``,
    `_Generated by HEAVEN-GeoIntel v${APP_VERSION} — for authorized use only. Verify all intelligence before relying on it._`,
  ].join("\n");
}

// ── Interop exports ──────────────────────────────────────────────────────────
// Quote every field AND neutralise CSV formula-injection: a cell beginning with
// = + - @ (or a tab/CR) is executed as a formula by Excel / Google Sheets. OSINT
// values are attacker-influenced (a phone is "+1…", a note is free text), so we
// prefix those with a single quote — the standard, lossless mitigation.
const csvEsc = (s: unknown) => {
  let v = String(s ?? "");
  if (/^[=+\-@\t\r]/.test(v)) v = "'" + v;
  return `"${v.replace(/"/g, '""')}"`;
};

/** Plain CSV of the case's identifiers. */
export function buildCaseCsv(c: InvestigationCase): string {
  const p = payloadOf(c);
  const rows = [["kind", "value", "addedAt", "note"].join(",")];
  for (const e of p.entities) {
    rows.push([e.kind, e.value, new Date(e.addedAt).toISOString(), e.note ?? ""].map(csvEsc).join(","));
  }
  return rows.join("\r\n");
}

/** Maltego "paste table" CSV — Entity Type + Value, one row per identifier. */
export function buildMaltegoCsv(c: InvestigationCase): string {
  const TYPE: Record<string, string> = {
    phone: "maltego.PhoneNumber", email: "maltego.EmailAddress",
    username: "maltego.Alias", ip: "maltego.IPv4Address", domain: "maltego.Domain",
  };
  const rows = [["Entity Type", "Value"].join(",")];
  for (const e of payloadOf(c).entities) {
    rows.push([TYPE[e.kind] ?? "maltego.Phrase", e.value].map(csvEsc).join(","));
  }
  return rows.join("\r\n");
}

/** STIX 2.1 bundle of Cyber-observable objects (SCOs) for the identifiers. */
export function buildStixBundle(c: InvestigationCase): string {
  const p = payloadOf(c);
  const uuid = () => (crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(16).slice(2));
  const objects: Record<string, unknown>[] = [
    { type: "identity", spec_version: "2.1", id: `identity--${uuid()}`, name: "HEAVEN-GeoIntel", identity_class: "system" },
  ];
  for (const e of p.entities) {
    const id = uuid();
    switch (e.kind) {
      case "email":    objects.push({ type: "email-addr",  spec_version: "2.1", id: `email-addr--${id}`,  value: e.value }); break;
      case "ip":       objects.push({ type: "ipv4-addr",   spec_version: "2.1", id: `ipv4-addr--${id}`,   value: e.value }); break;
      case "domain":   objects.push({ type: "domain-name", spec_version: "2.1", id: `domain-name--${id}`, value: e.value }); break;
      case "username": objects.push({ type: "user-account",spec_version: "2.1", id: `user-account--${id}`,account_login: e.value }); break;
      case "phone":    objects.push({ type: "x-phone-number", spec_version: "2.1", id: `x-phone-number--${id}`, value: e.value }); break;
    }
  }
  return JSON.stringify({ type: "bundle", id: `bundle--${uuid()}`, objects }, null, 2);
}

/** Self-contained printable HTML (for browser "Save as PDF"). */
export async function buildPrintableHtml(c: InvestigationCase): Promise<string> {
  const md = await buildCaseMarkdown(c);
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>HEAVEN-GeoIntel — ${esc(c.name)}</title>
<style>
  body{font:13px/1.6 ui-monospace,Menlo,Consolas,monospace;max-width:820px;margin:32px auto;padding:0 20px;color:#0b1020}
  pre{white-space:pre-wrap;word-break:break-word}
  @media print{@page{margin:14mm}}
</style></head><body><pre>${esc(md)}</pre>
<script>window.onload=function(){setTimeout(function(){window.print()},250)}</script>
</body></html>`;
}

export interface ImportCheck {
  ok: boolean;
  case?: CasePayload;
  expectedHash?: string;
  actualHash?: string;
  error?: string;
  tampered?: boolean;
}

/** Parse + integrity-check a previously exported JSON report (no network). */
export async function verifyCaseImport(text: string): Promise<ImportCheck> {
  let parsed: unknown;
  try { parsed = JSON.parse(text); }
  catch { return { ok: false, error: "Not valid JSON" }; }

  const env = parsed as Partial<CaseReportEnvelope>;
  if (!env || env.schema !== REPORT_SCHEMA || !env.case) {
    return { ok: false, error: "Not a HEAVEN-GeoIntel case report" };
  }
  const payload = payloadOf({
    id: "", createdAt: env.case.createdAt ?? Date.now(), updatedAt: env.case.updatedAt ?? Date.now(),
    name: env.case.name ?? "", entities: (env.case.entities ?? []) as CaseEntity[], notes: env.case.notes ?? "",
  });
  const actualHash = await sha256Hex(canonical(payload));
  const expectedHash = env.integrity?.hash;
  const tampered = Boolean(expectedHash && expectedHash !== actualHash);
  return { ok: true, case: payload, expectedHash, actualHash, tampered };
}
