# HEAVEN-GeoIntel — terminal banner.
#
# GENERATED by `npm run brand` from src/lib/brand/banner.ts — do not edit.
# tests/posterAssets.test.ts fails the build if this file drifts from that
# module, so the banner cannot go stale after a version or source change.
#
# Sourced by start.sh, install-global.sh and uninstall-global.sh.
# hv_banner prints colour on a TTY, plain text when piped or under NO_COLOR.

hv_banner() {
  if [ -n "${NO_COLOR:-}" ] || [ ! -t 1 ]; then
    hv_banner_plain
  else
    hv_banner_color
  fi
}

hv_banner_plain() {
  printf '%s\n' '╭────────────────────────────────────────────────────────────────────╮'
  printf '%s\n' '│   ▄▀▀▀▀▀▄                                                          │'
  printf '%s\n' '│  ▐  █ █  ▌   HEAVEN-GeoIntel  v2.0.0                               │'
  printf '%s\n' '│  ▐  ███  ▌   UNIFIED OSINT PLATFORM                                │'
  printf '%s\n' '│  ▐  █ █  ▌                                                         │'
  printf '%s\n' '│   ▀▄▄▄▄▄▀    5 identifiers · 8 modes · 13/21 sources need no key   │'
  printf '%s\n' '╰────────────────────────────────────────────────────────────────────╯'
}

hv_banner_color() {
  printf '%s\n' '[38;5;44m╭────────────────────────────────────────────────────────────────────╮[0m'
  printf '%s\n' '[38;5;44m│[0m[38;5;44m  [0m[38;5;48m ▄▀▀▀▀▀▄ [0m[38;5;44m   [0m[38;5;44m                                                      [0m[38;5;44m│[0m'
  printf '%s\n' '[38;5;44m│[0m[38;5;44m  [0m[38;5;48m▐  █ █  ▌[0m[38;5;44m   [0m[1;38;5;48mHEAVEN[0m[38;5;66m-[0m[1;38;5;48mGeoIntel[0m[38;5;66m  [0m[38;5;44mv2.0.0[0m[38;5;44m                               [0m[38;5;44m│[0m'
  printf '%s\n' '[38;5;44m│[0m[38;5;44m  [0m[38;5;48m▐  ███  ▌[0m[38;5;44m   [0m[38;5;108mUNIFIED OSINT PLATFORM[0m[38;5;44m                                [0m[38;5;44m│[0m'
  printf '%s\n' '[38;5;44m│[0m[38;5;44m  [0m[38;5;48m▐  █ █  ▌[0m[38;5;44m   [0m[38;5;44m                                                      [0m[38;5;44m│[0m'
  printf '%s\n' '[38;5;44m│[0m[38;5;44m  [0m[38;5;48m ▀▄▄▄▄▄▀ [0m[38;5;44m   [0m[38;5;66m5 identifiers[0m[38;5;44m · [0m[38;5;66m8 modes[0m[38;5;44m · [0m[38;5;66m13/21 sources need no key[0m[38;5;44m   [0m[38;5;44m│[0m'
  printf '%s\n' '[38;5;44m╰────────────────────────────────────────────────────────────────────╯[0m'
}
