#!/usr/bin/env node
/**
 * Generate the README poster and the terminal banner.
 *
 *   npm run brand:poster        (or: npm run brand, which also does the PNGs)
 *
 * Deliberately separate from generate-brand-assets.mjs, which launches Chrome
 * to rasterise PNGs. Nothing here needs a browser, so the poster and the
 * launcher banner can always be regenerated — including on a machine with no
 * Chrome, and in CI.
 *
 * The numbers come from scripts/poster-stats.mjs, which reads them out of the
 * real registries. tests/posterAssets.test.ts re-derives them the same way and
 * fails if the committed artwork is stale, so "remember to run npm run brand"
 * is enforced rather than hoped for.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { posterSvg } from "../src/lib/brand/poster.ts";
import { bannerPlain, bannerAnsi, bannerTrueColor } from "../src/lib/brand/banner.ts";
import { posterStats } from "./poster-stats.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC_BRAND = join(ROOT, "public", "brand");
await mkdir(PUBLIC_BRAND, { recursive: true });

const STATS = posterStats(ROOT);
console.log("poster stats, all derived from source:");
console.log(JSON.stringify(STATS, null, 2));

// ── The poster ──────────────────────────────────────────────────────────────
// Dark and light are separate files rather than one file with a media query,
// because <picture> is how a README switches artwork with the reader's theme,
// and that needs two URLs.
const posters = {
  "poster.svg": posterSvg(STATS, { theme: "dark" }),
  "poster-light.svg": posterSvg(STATS, { theme: "light" }),
  // A still frame for print, and for anything that strips CSS animation.
  "poster-still.svg": posterSvg(STATS, { theme: "dark", animated: false }),
};
for (const [name, svg] of Object.entries(posters)) {
  await writeFile(join(PUBLIC_BRAND, name), svg + "\n", "utf8");
  console.log("wrote public/brand/" + name);
}

// ── The terminal banner ─────────────────────────────────────────────────────
// Single-quoted shell literals holding raw ANSI bytes: the shell does no
// interpretation inside them, so there is nothing to escape wrongly.
const emit = (lines) => lines.map((l) => `  printf '%s\\n' '${l}'`).join("\n");

await writeFile(
  join(ROOT, "scripts", "banner.sh"),
  `# HEAVEN-GeoIntel — terminal banner.
#
# GENERATED by \`npm run brand\` from src/lib/brand/banner.ts — do not edit.
# tests/posterAssets.test.ts fails the build if this file drifts from that
# module, so the banner cannot go stale after a version or source change.
#
# Sourced by start.sh, install-global.sh and uninstall-global.sh.
# hv_banner picks the richest tier the terminal can render: a 24-bit gradient
# when COLORTERM advertises truecolor, 256-colour on any other TTY, and plain
# text when piped or under NO_COLOR.

hv_banner() {
  if [ -n "\${NO_COLOR:-}" ] || [ ! -t 1 ]; then
    hv_banner_plain
  elif [ "\${COLORTERM:-}" = "truecolor" ] || [ "\${COLORTERM:-}" = "24bit" ]; then
    hv_banner_truecolor
  else
    hv_banner_color
  fi
}

hv_banner_plain() {
${emit(bannerPlain(STATS))}
}

hv_banner_color() {
${emit(bannerAnsi(STATS))}
}

hv_banner_truecolor() {
${emit(bannerTrueColor(STATS))}
}
`,
  "utf8",
);
console.log("wrote scripts/banner.sh");
